from .DL_stamp_duty import StampDutyTypeDL

stamp_duty_display_names_DL = {
    StampDutyTypeDL.DL_RG_97: "Acknowledgement of a debt [1]",
    StampDutyTypeDL.DL_RG_16: "Additional Copy of document [25]",
    StampDutyTypeDL.DL_RG_1: "Adoption [3]",
    StampDutyTypeDL.DL_RG_78: "Affidavit [4]",
    StampDutyTypeDL.DL_RG_6: "Agreement relating to deposit of title deed [6(2)(a)]",
    StampDutyTypeDL.DL_RG_7: "Agreement relating to deposit of title deed [6(2)(b)]",
    StampDutyTypeDL.DL_RG_69: "Assignment of Debt [11(Sch-1A)]",
    StampDutyTypeDL.DL_RG_60: "Authority to Adopt [11]",
    StampDutyTypeDL.DL_RG_8: "Award [12]",
    StampDutyTypeDL.DL_RG_10: "Award - Immovable [12]",
    StampDutyTypeDL.DL_RG_9: "Award - Movable [12]",
    StampDutyTypeDL.DL_RG_81: "Bank Guarantee [ ]",
    StampDutyTypeDL.DL_RG_93: "Bill of Exchange [13]",
    StampDutyTypeDL.DL_RG_87: "Bond [ ]",
    StampDutyTypeDL.DL_RG_94: "Bonds [15]",
    StampDutyTypeDL.DL_RG_76: "Cancellation Of Will [ ]",
    StampDutyTypeDL.DL_RG_61: "Cancellation of Agreement [17]",
    StampDutyTypeDL.DL_RG_12: "Cancellation of instrument [17]",
    StampDutyTypeDL.DL_RG_83: "Car Loan/ Loan Agreement [ ]",
    StampDutyTypeDL.DL_RG_13: "Certificate of Sale [18]",
    StampDutyTypeDL.DL_RG_95: "Certificate or other document (Shares) [19]",
    StampDutyTypeDL.DL_RG_59: "Consent Letter [5]",
    StampDutyTypeDL.DL_RG_14: "Conveyance [23]",
    StampDutyTypeDL.DL_RG_88: "Conveyance (M&A of Companies under Amalgamation Scheme) [23]",
    StampDutyTypeDL.DL_RG_98: "Customs-Bonds [26]",
    StampDutyTypeDL.DL_RG_92: "Debenture [27]",
    StampDutyTypeDL.DL_RG_2: "Declaration [4]",
    StampDutyTypeDL.DL_RG_63: "Decree(Sale Deed/Conveyance) [23]",
    StampDutyTypeDL.DL_RG_65: "Decree(Settlement) [58]",
    StampDutyTypeDL.DL_RG_68: "Deed of Retirement [64(b)]",
    StampDutyTypeDL.DL_RG_50: "Disclaimer [55]",
    StampDutyTypeDL.DL_RG_67: "Dissolution Deed [64(b)]",
    StampDutyTypeDL.DL_RG_17: "Divorce [29]",
    StampDutyTypeDL.DL_RG_18: "Exchange of property [31]",
    StampDutyTypeDL.DL_RG_86: "Forward Contract [ ]",
    StampDutyTypeDL.DL_RG_21: "Further Charge [32(b)(ii)]",
    StampDutyTypeDL.DL_RG_20: "Further Charge [32(b)(i)]",
    StampDutyTypeDL.DL_RG_19: "Further Charge [32(a)]",
    StampDutyTypeDL.DL_RG_70: "GPA-Blood Relation [48]",
    StampDutyTypeDL.DL_RG_3: "General Agreement [5]",
    StampDutyTypeDL.DL_RG_22: "Gift [33]",
    StampDutyTypeDL.DL_RG_82: "Guarantee Bond [ ]",
    StampDutyTypeDL.DL_RG_99: "Indemnity Bond [34]",
    StampDutyTypeDL.DL_RG_11: "Indemnity Bond [15]",
    StampDutyTypeDL.DL_RG_85: "L.C. (Letter Certificate) [ ]",
    StampDutyTypeDL.DL_RG_26: "Lease upto 10 years [35(iii)]",
    StampDutyTypeDL.DL_RG_29: "Lease upto 100 years [35(vi)]",
    StampDutyTypeDL.DL_RG_27: "Lease upto 20 years [35(iv)]",
    StampDutyTypeDL.DL_RG_30: "Lease upto 200 years [35(vii)]",
    StampDutyTypeDL.DL_RG_28: "Lease upto 30 years [35(v)]",
    StampDutyTypeDL.DL_RG_25: "Lease upto 5 years [35(ii)]",
    StampDutyTypeDL.DL_RG_32: "Lease with security upto 10 years [35(iii)]",
    StampDutyTypeDL.DL_RG_35: "Lease with security upto 100 years [35(vi)]",
    StampDutyTypeDL.DL_RG_33: "Lease with security upto 20 years [35(iv)]",
    StampDutyTypeDL.DL_RG_36: "Lease with security upto 200 years [35(vii)]",
    StampDutyTypeDL.DL_RG_34: "Lease with security upto 30 years [35(v)]",
    StampDutyTypeDL.DL_RG_31: "Lease with security upto 5 years [35(ii)]",
    StampDutyTypeDL.DL_RG_100: "Lease- Rent deed less than 1 year [35(i)]",
    StampDutyTypeDL.DL_RG_24: "Lease- Rent deed upto 1 year [35(i)]",
    StampDutyTypeDL.DL_RG_66: "Memorandum of Settlement [58]",
    StampDutyTypeDL.DL_RG_37: "Mortgage [40]",
    StampDutyTypeDL.DL_RG_38: "Mortgage Collateral [40(c)]",
    StampDutyTypeDL.DL_RG_64: "Mortgage of a Crop [41]",
    StampDutyTypeDL.DL_RG_77: "Others [ ]",
    StampDutyTypeDL.DL_RG_39: "Partition [45]",
    StampDutyTypeDL.DL_RG_40: "Partnership [46]",
    StampDutyTypeDL.DL_RG_23: "Perpetual [35]",
    StampDutyTypeDL.DL_RG_91: "Policy of Insurance [47]",
    StampDutyTypeDL.DL_RG_46: "Power of attorney - Authenticated GPA [48(g)]",
    StampDutyTypeDL.DL_RG_42: "Power of attorney - GPA [48(c)]",
    StampDutyTypeDL.DL_RG_44: "Power of attorney - GPA more than five persons but less than ten persons [48(e)]",
    StampDutyTypeDL.DL_RG_43: "Power of attorney - GPA more than five persons jointly and severly [48(d)]",
    StampDutyTypeDL.DL_RG_41: "Power of attorney -SPA [48]",
    StampDutyTypeDL.DL_RG_45: "Power of attorney- GPA with consideration [48(f)]",
    StampDutyTypeDL.DL_RG_48: "Re-conveyance [54]",
    StampDutyTypeDL.DL_RG_47: "Receipt [53]",
    StampDutyTypeDL.DL_RG_96: "Record of Transaction (Electronics or Otherwise) effected by a trading member (Broker Note) [54A]",
    StampDutyTypeDL.DL_RG_4: "Rectification Deed- Immovable [5(c)]",
    StampDutyTypeDL.DL_RG_5: "Rectification Deed- Movable [5(c)]",
    StampDutyTypeDL.DL_RG_51: "Release [55]",
    StampDutyTypeDL.DL_RG_49: "Relinquishment Deed [55]",
    StampDutyTypeDL.DL_RG_52: "Respondentia Bond [56]",
    StampDutyTypeDL.DL_RG_58: "Revocation of Trust [64(b)]",
    StampDutyTypeDL.DL_RG_62: "Sale [23]",
    StampDutyTypeDL.DL_RG_15: "Sale Agreement [23-A]",
    StampDutyTypeDL.DL_RG_53: "Security Bond [57]",
    StampDutyTypeDL.DL_RG_54: "Settlement [58]",
    StampDutyTypeDL.DL_RG_89: "Share Warrants [59]",
    StampDutyTypeDL.DL_RG_80: "Surety Bonds [ ]",
    StampDutyTypeDL.DL_RG_55: "Surrender of Lease [61]",
    StampDutyTypeDL.DL_RG_90: "Transfer (with or without consideration for Debentures & Company Shares) [62]",
    StampDutyTypeDL.DL_RG_84: "Transfer Deed [ ]",
    StampDutyTypeDL.DL_RG_56: "Transfer of Lease [63]",
    StampDutyTypeDL.DL_RG_57: "Trust [64]",
    StampDutyTypeDL.DL_RG_79: "Undertaking [ ]",
    StampDutyTypeDL.DL_RG_71: "Will [ ]",
    StampDutyTypeDL.DL_RG_74: "Will After Death [ ]",
    StampDutyTypeDL.DL_RG_75: "Will Medical Ground [ ]",
    StampDutyTypeDL.DL_RG_73: "Will Sealed Cover [ ]",
    StampDutyTypeDL.DL_RG_72: "Will With Cancellation [ ]",
}