from .gj_stamp_duty import StampDutyTypeGujarat

stamp_duty_display_names_gujarat = {
    StampDutyTypeGujarat.GJ_NRG_30: "Administration Bond [2]",
    StampDutyTypeGujarat.GJ_RG_31: "Adoption - Deed [3]",
    StampDutyTypeGujarat.GJ_NRG_32: "Affidavit [4]",
    StampDutyTypeGujarat.GJ_NRG_33H: "Agreement (not otherwise provided for) [5(h)]",
    StampDutyTypeGujarat.GJ_NRG_33: "Agreement - Construction / Development / Sale / Transfer (Imm. Property) [5(g-a)]",
    StampDutyTypeGujarat.GJ_RG_92: "Agreement - Construction / Development / Sale / Transfer (Imm. Property) [5(g-a)]",
    StampDutyTypeGujarat.GJ_NRG_33I: "Agreement - Media Advertisement - Other than Newspapers [5(gb)]",
    StampDutyTypeGujarat.GJ_NRG_33E: "Agreement - Purchase or Sale of Bullion, Spice [5(e)]",
    StampDutyTypeGujarat.GJ_NRG_33D: "Agreement - Purchase or Sale of Cotton [5(d)]",
    StampDutyTypeGujarat.GJ_NRG_33B: "Agreement - Purchase or Sale of Govt. Sec. [5(b)]",
    StampDutyTypeGujarat.GJ_NRG_33F: "Agreement - Purchase or Sale of Oil Seeds [5(f)]",
    StampDutyTypeGujarat.GJ_NRG_33C: "Agreement - Purchase or Sale of Share, Deb. [5(c)]",
    StampDutyTypeGujarat.GJ_NRG_33G: "Agreement - Purchase or Sale of Yarn [5(g)]",
    StampDutyTypeGujarat.GJ_NRG_33A: "Agreement - Sale of Bill of Exchange [5(a)]",
    StampDutyTypeGujarat.GJ_NRG_121: "Agreement For Project under BOT, Concession, PPP Or Not cover under any other Articles [5(gc)]",
    StampDutyTypeGujarat.GJ_NRG_86: "Agreement relating to Purchase or Sale of Shares, Debentures etc [5(c)]",
    StampDutyTypeGujarat.GJ_RG_1: "Agreement to Sale [5(h)]",
    StampDutyTypeGujarat.GJ_NRG_36: "Alteration - Article of Association of a Company [7]",
    StampDutyTypeGujarat.GJ_NRG_37: "Alteration - Memorandum of Association of a Company [8]",
    StampDutyTypeGujarat.GJ_NRG_127: "Alteration - Memorandum of Association of a Company Without Article of Association [8(b)]",
    StampDutyTypeGujarat.GJ_NRG_126: "Alteration - Memorandum of Association of a Company with Article of Association [8(a)]",
    StampDutyTypeGujarat.GJ_NRG_1: "Application- under RTI Act [99]",
    StampDutyTypeGujarat.GJ_NRG_39: "Appointment in Execution of Power - Movable / Immovable [9(b)]",
    StampDutyTypeGujarat.GJ_NRG_38: "Appointment in Execution of Power - Trustees [9(a)]",
    StampDutyTypeGujarat.GJ_NRG_40: "Appraisement or Valuation [10]",
    StampDutyTypeGujarat.GJ_NRG_41: "Apprenticeship Deed [11]",
    StampDutyTypeGujarat.GJ_NRG_42: "Article of Association of Company [12]",
    StampDutyTypeGujarat.GJ_NRG_122: "Articles of Association [12]",
    StampDutyTypeGujarat.GJ_NRG_43: "Award [13]",
    StampDutyTypeGujarat.GJ_NRG_44: "Bond [14]",
    StampDutyTypeGujarat.GJ_NRG_112: "Bond - Above Rs. 10 Crore [14]",
    StampDutyTypeGujarat.GJ_NRG_111: "Bond - Up To Rs. 10 Crore [14]",
    StampDutyTypeGujarat.GJ_NRG_125: "Bond- Exceed Rs. 10 Cr. [14(iii)]",
    StampDutyTypeGujarat.GJ_NRG_124: "Bond- From Rs. 1 Cr. To 10 Cr. [14(ii)]",
    StampDutyTypeGujarat.GJ_NRG_123: "Bond- Not Exceed Rs. 1 Cr. [14(i)]",
    StampDutyTypeGujarat.GJ_NRG_45: "Bottomry Bond [15]",
    StampDutyTypeGujarat.GJ_NRG_114: "Bottomry Bond - Above Rs. 10 Crore [15]",
    StampDutyTypeGujarat.GJ_NRG_113: "Bottomry Bond - Up To Rs. 10 Crore [15]",
    StampDutyTypeGujarat.GJ_RG_46: "Cancellation [16]",
    StampDutyTypeGujarat.GJ_RG_41: "Cancellation for Immovable - Property [16]",
    StampDutyTypeGujarat.GJ_NRG_2: "Cancellation for movable - Property [16]",
    StampDutyTypeGujarat.GJ_RG_2: "Certificate of Sale [17]",
    StampDutyTypeGujarat.GJ_NRG_47: "Certificate or Other Document [18]",
    StampDutyTypeGujarat.GJ_NRG_51: "Clearance List - Bullion or Species [18 C]",
    StampDutyTypeGujarat.GJ_NRG_50: "Clearance List - Cotton [18 B]",
    StampDutyTypeGujarat.GJ_NRG_48: "Clearance List - Govt. Sec. [18 A(1)]",
    StampDutyTypeGujarat.GJ_NRG_52: "Clearance List - Oil Seeds [18 D]",
    StampDutyTypeGujarat.GJ_NRG_49: "Clearance List - Shares, Debentures [18 A(2)]",
    StampDutyTypeGujarat.GJ_NRG_54: "Clearance List - Yarn [18 E]",
    StampDutyTypeGujarat.GJ_NRG_55: "Composition Deed [19]",
    StampDutyTypeGujarat.GJ_RG_3: "Conveyance - Immovable Property [20(a)]",
    StampDutyTypeGujarat.GJ_NRG_56: "Conveyance - Movable Property [20 (aa)]",
    StampDutyTypeGujarat.GJ_RG_4: "Conveyance - Property of Co-Op Soc. [20(b)]",
    StampDutyTypeGujarat.GJ_RG_5: "Conveyance - Property of N.T.C, G.H.B., G.O.F.A. [20(c)]",
    StampDutyTypeGujarat.GJ_RG_6: "Conveyance Amalgamation / Reconstruction of Company [20(d)]",
    StampDutyTypeGujarat.GJ_RG_99: "Conveyance Amalgamation, Merger, Demerger, Arrangement, Reconstruction Order by NCLT, RBI, BIFR, IBC etc. [20(d)(i)]",
    StampDutyTypeGujarat.GJ_NRG_57: "Copy or Extract [21]",
    StampDutyTypeGujarat.GJ_NRG_129: "Copy or Extract - For Birth, Death, Name Change, Marriage, Divorce etc. [21(b)]",
    StampDutyTypeGujarat.GJ_NRG_128: "Copy or Extract - For and By Government [21(a)]",
    StampDutyTypeGujarat.GJ_NRG_58: "Counter Part or Duplicate [22]",
    StampDutyTypeGujarat.GJ_NRG_59: "Customs Bond or Excise Bond [23]",
    StampDutyTypeGujarat.GJ_NRG_60: "Delivery Order in respect of Goods [24]",
    StampDutyTypeGujarat.GJ_RG_34: "Deposit of Title Deeds [6(1)]",
    StampDutyTypeGujarat.GJ_RG_95: "Deposit of Title Deeds - Loan/Debt Exceeds Rs. 10 Cr. [6(1)(a)(iii)]",
    StampDutyTypeGujarat.GJ_RG_93: "Deposit of Title Deeds - Loan/Debt Not Exceed Rs. 1 Cr. [6(1)(a)(i)]",
    StampDutyTypeGujarat.GJ_RG_119: "Deposit of Title Deeds - Loan/Debt from Rs. 1 Cr. To Rs. 10 Cr. [6(1)(a)(ii)]",
    StampDutyTypeGujarat.GJ_NRG_61: "Divorce [25]",
    StampDutyTypeGujarat.GJ_RG_7: "Exchange of Property [26]",
    StampDutyTypeGujarat.GJ_RG_7A: "Further Charge - With Possession [27(a)]",
    StampDutyTypeGujarat.GJ_RG_7B: "Further Charge - Without Possession [27(b)]",
    StampDutyTypeGujarat.GJ_RG_102: "Further Charge - Without Possession Exceeds Rs. 10 Cr. [27(b)(iii)]",
    StampDutyTypeGujarat.GJ_RG_100: "Further Charge - Without Possession Not Exceed Rs. 1 Cr. [27(b)(i)]",
    StampDutyTypeGujarat.GJ_RG_101: "Further Charge- Without Possession from Rs. 1 Cr. To Rs. 10 Cr. [27(b)(ii)]",
    StampDutyTypeGujarat.GJ_RG_8: "Gift [28]",
    StampDutyTypeGujarat.GJ_NRG_62: "Indemnity Bond [29]",
    StampDutyTypeGujarat.GJ_RG_10: "Lease - (Imm. Property) - Premium or Money Adv. [30(b)]",
    StampDutyTypeGujarat.GJ_RG_11: "Lease - (Imm. Property) - Rent + Premium or Money Adv. [30(c)]",
    StampDutyTypeGujarat.GJ_RG_9: "Lease - (Immovable Property) - Rent [30(a)]",
    StampDutyTypeGujarat.GJ_NRG_64: "Lease - Movable Property [30 D]",
    StampDutyTypeGujarat.GJ_RG_106: "Lease 1 Year To 5 Years Commercial Property [30(a)(ii)]",
    StampDutyTypeGujarat.GJ_RG_105: "Lease 1 Year To 5 Years Residential Property [30(a)(ii)]",
    StampDutyTypeGujarat.GJ_RG_108: "Lease 15 Years To 30 Years [30(a)(iv)]",
    StampDutyTypeGujarat.GJ_RG_109: "Lease 30 Years To 99 Years [30(a)(v)]",
    StampDutyTypeGujarat.GJ_RG_107: "Lease 5 Years To 15 Years [30(a)(iii)]",
    StampDutyTypeGujarat.GJ_RG_110: "Lease Excess 99 Years [30(a)(vi)]",
    StampDutyTypeGujarat.GJ_RG_104: "Lease Less than 1 Year Commercial Property [30(a)(i)]",
    StampDutyTypeGujarat.GJ_RG_103: "Lease Less than 1 Year Residential Property [30(a)(i)]",
    StampDutyTypeGujarat.GJ_NRG_3: "Lease of immovable property - Not exceeding one year [30(a)(1)]",
    StampDutyTypeGujarat.GJ_RG_63: "Leave and License Agreement [30 A]",
    StampDutyTypeGujarat.GJ_NRG_65: "Letter of Allotment or Renunciation of Shares [31]",
    StampDutyTypeGujarat.GJ_NRG_66: "Letter of Guarantee [32]",
    StampDutyTypeGujarat.GJ_NRG_67: "Letter of License [33]",
    StampDutyTypeGujarat.GJ_NRG_68: "Marriage Registration [34]",
    StampDutyTypeGujarat.GJ_NRG_69: "Memorandum of Association of Company [35]",
    StampDutyTypeGujarat.GJ_RG_29: "Memorandum of Association of Company [35(a)]",
    StampDutyTypeGujarat.GJ_NRG_131: "Memorandum of Association of Company - Without Article of Association [35(b)]",
    StampDutyTypeGujarat.GJ_NRG_130: "Memorandum of Association of Company- With Article of Association [35(a)]",
    StampDutyTypeGujarat.GJ_RG_12: "Mortgage Deed - With Possession [36(a)]",
    StampDutyTypeGujarat.GJ_RG_111: "Mortgage Deed - With Possession-Additional Collateral [36(c)]",
    StampDutyTypeGujarat.GJ_RG_13: "Mortgage Deed - Without Possession [36(b)]",
    StampDutyTypeGujarat.GJ_NRG_71: "Mortgage of Crop [37 (b)]",
    StampDutyTypeGujarat.GJ_NRG_70: "Mortgage of Crop - Not more than 3 months [37 (a)]",
    StampDutyTypeGujarat.GJ_NRG_72: "Notarial Act [38]",
    StampDutyTypeGujarat.GJ_NRG_81: "Note of Protest by the Master of a Ship [41]",
    StampDutyTypeGujarat.GJ_NRG_80: "Note or Entry or Letter Written by Creditor [40]",
    StampDutyTypeGujarat.GJ_NRG_74: "Note or Memorandum - Bullion / Specie [39 (b)]",
    StampDutyTypeGujarat.GJ_NRG_73: "Note or Memorandum - Cotton [39 (a)]",
    StampDutyTypeGujarat.GJ_NRG_77: "Note or Memorandum - Goods (other than Article 39 a,b,c,d) [39 (e)]",
    StampDutyTypeGujarat.GJ_NRG_79: "Note or Memorandum - Govt. Security [39 (g)]",
    StampDutyTypeGujarat.GJ_NRG_75: "Note or Memorandum - Oil Seeds [39 (c)]",
    StampDutyTypeGujarat.GJ_NRG_78: "Note or Memorandum - Stocks / Debenture [39 (f)]",
    StampDutyTypeGujarat.GJ_NRG_76: "Note or Memorandum - Yarn / Non Mineral Oils [39 (d)]",
    StampDutyTypeGujarat.GJ_NRG_83: "Order for the Payment of Money - More than 1 year [42 (b)]",
    StampDutyTypeGujarat.GJ_NRG_116: "Order for the Payment of Money - More than 1 year - Above 10 Crore [42(b)]",
    StampDutyTypeGujarat.GJ_NRG_115: "Order for the Payment of Money - More than 1 year - Up to 10 Crore [42(b)]",
    StampDutyTypeGujarat.GJ_NRG_82: "Order for the Payment of Money - Not more than 1 year [42 (a)]",
    StampDutyTypeGujarat.GJ_RG_14: "Partitioned [43]",
    StampDutyTypeGujarat.GJ_NRG_84: "Partnership [44]",
    StampDutyTypeGujarat.GJ_RG_39: "Partnership - Alteration ( Other than clause a.) [44(2)(b)]",
    StampDutyTypeGujarat.GJ_RG_15: "Partnership - Dissolution [44(3)(a)]",
    StampDutyTypeGujarat.GJ_RG_40: "Partnership - Dissolution in any other case [44(3)(b)]",
    StampDutyTypeGujarat.GJ_NRG_85: "Partnership - Dissolution in any other case [44(3)(b)]",
    StampDutyTypeGujarat.GJ_RG_113: "Partnership [1] (a)- by Cash [44(1)(a)]",
    StampDutyTypeGujarat.GJ_RG_114: "Partnership [1] (b)- by Immovable Property [44(1)(b)]",
    StampDutyTypeGujarat.GJ_RG_115: "Partnership [1] (c)- by Cash and Immovable Property [44(1)(c)]",
    StampDutyTypeGujarat.GJ_NRG_132: "Partnership [2] (a)- by Constitution Alteration - Capital Increase [44(2)(a)]",
    StampDutyTypeGujarat.GJ_RG_35: "Pledge, Loan or Hypothecation - Movable Property [6(2)]",
    StampDutyTypeGujarat.GJ_RG_98: "Pledge, Loan or Hypothecation - Movable Property Loan/Debt Exceeds Rs. 10 Cr. [6(2)(a)(iii)]",
    StampDutyTypeGujarat.GJ_RG_97: "Pledge, Loan or Hypothecation - Movable Property Loan/Debt from Rs. 1 Cr to Rs. 10 Cr. [6(2)(a)(ii)]",
    StampDutyTypeGujarat.GJ_RG_96: "Pledge, Loan or Hypothecation - Movable Property Loan/Debt not Exceed Rs. 1 Cr [6(2)(a)(i)]",
    StampDutyTypeGujarat.GJ_RG_90: "Power of Attorney (Development) [45 (g)]",
    StampDutyTypeGujarat.GJ_RG_91: "Power of Attorney (in any other case) [45 (h)]",
    StampDutyTypeGujarat.GJ_NRG_99: "Power of Attorney (relating to movable property) [45]",
    StampDutyTypeGujarat.GJ_RG_16: "Power of Attorney - For Consideration - Sale of Imm. Property [45(f)]",
    StampDutyTypeGujarat.GJ_RG_116: "Power of Attorney - For Consideration - Sale of Immovable Property [45(f)(i)]",
    StampDutyTypeGujarat.GJ_RG_36: "Power of Attorney - Imovable Property [45(f)(ii)(a)]",
    StampDutyTypeGujarat.GJ_RG_89: "Power of Attorney - More than 5 persons [45 (e)]",
    StampDutyTypeGujarat.GJ_RG_87: "Power of Attorney - Other than Article 45 (a) [45 (c)]",
    StampDutyTypeGujarat.GJ_RG_85: "Power of Attorney - Registration of Document - Single Transaction [45 (a)]",
    StampDutyTypeGujarat.GJ_RG_33: "Power of Attorney - Registration of Document - Sole Purpose [45(a)]",
    StampDutyTypeGujarat.GJ_RG_117: "Power of Attorney - Sale of Immovable Property by Relative [45(f)(ii)(a)]",
    StampDutyTypeGujarat.GJ_RG_118: "Power of Attorney - Sale of Immovable Property other than Relative [45(f)(ii)(b)]",
    StampDutyTypeGujarat.GJ_RG_86: "Power of Attorney - Suits - Small Cause Courts Act. [45 (b)]",
    StampDutyTypeGujarat.GJ_RG_88: "Power of Attorney -Not More than 5 persons [45 (d)]",
    StampDutyTypeGujarat.GJ_NRG_93: "Protest by the Master of a Ship [47]",
    StampDutyTypeGujarat.GJ_NRG_92: "Protest of Bill or Note [46]",
    StampDutyTypeGujarat.GJ_RG_17: "Reconveyance of Mortgaged Property [48]",
    StampDutyTypeGujarat.GJ_RG_37: "Record of Transaction [48-A(a)]",
    StampDutyTypeGujarat.GJ_RG_94: "Release [49]",
    StampDutyTypeGujarat.GJ_RG_38: "Release- Ancestral Property [49(a)]",
    StampDutyTypeGujarat.GJ_RG_112: "Release- In Any Other Case [49(b)]",
    StampDutyTypeGujarat.GJ_NRG_95: "Respondentia Bond [50]",
    StampDutyTypeGujarat.GJ_NRG_118: "Respondentia Bond - Above Rs. 10 Crore [50]",
    StampDutyTypeGujarat.GJ_NRG_117: "Respondentia Bond - Up To Rs. 10 Crore [50]",
    StampDutyTypeGujarat.GJ_NRG_96: "Security Bond or Mortgage - Deed [51]",
    StampDutyTypeGujarat.GJ_RG_19: "Settlement - Other Case [52 A(ii)]",
    StampDutyTypeGujarat.GJ_RG_18: "Settlement - Religious or Charitable purpose [52 A(i)]",
    StampDutyTypeGujarat.GJ_RG_21: "Settlement - Revocation - Other Case [52 B(ii)]",
    StampDutyTypeGujarat.GJ_RG_20: "Settlement - Revocation - Religious or Charitable [52 B(i)]",
    StampDutyTypeGujarat.GJ_NRG_97: "Share Warrants [53]",
    StampDutyTypeGujarat.GJ_NRG_120: "Share Warrants - Above Rs. 10 Crore [53]",
    StampDutyTypeGujarat.GJ_NRG_119: "Share Warrants - Up To Rs. 10 Crore [53]",
    StampDutyTypeGujarat.GJ_RG_22: "Surrender of Lease [55]",
    StampDutyTypeGujarat.GJ_NRG_6: "The pawn, pledge or hypothecation of movable property, where such pawn, pledge or hypothecation has been made by way of security for the repayment of money advanced or to be advanced by way of loan or an existing or future debt [6(2)]",
    StampDutyTypeGujarat.GJ_RG_23: "Transfer - Interest Secured by Bond [56(b)]",
    StampDutyTypeGujarat.GJ_RG_25: "Transfer - Trustees or Beneficiary (Without - Consideration) [56(d)]",
    StampDutyTypeGujarat.GJ_RG_24: "Transfer - Under the Administrators Gen. Act 1963, Sec. 22 [56(c)]",
    StampDutyTypeGujarat.GJ_NRG_98: "Transfer of Debenture [56(a)]",
    StampDutyTypeGujarat.GJ_RG_26: "Transfer of Lease [57]",
    StampDutyTypeGujarat.GJ_RG_27: "Trust - Declaration [58(a)]",
    StampDutyTypeGujarat.GJ_RG_28: "Trust - Revocation [58(b)]",
}