from .kar_stamp_duty import StampDutyTypeKarnataka

stamp_duty_display_names_karnataka = {
    StampDutyTypeKarnataka.KA_NRG_5: "Acknowledge of a Debt - more than 5000/- [1(i)(b)]",
    StampDutyTypeKarnataka.KA_NRG_1: "Acknowledge of a Debt - upto Rs.5000/- [1(i)(a)]",
    StampDutyTypeKarnataka.KA_RG_23: "Acknowledgement [1]",
    StampDutyTypeKarnataka.KA_RG_75: "Acknowledgement of Debt [1(a)(b)]",
    StampDutyTypeKarnataka.KA_NRG_6: "Acknowledgement of Letter, Article, Package, Parcel ..... [1(ii)]",
    StampDutyTypeKarnataka.KA_NRG_129: "Acknowledgement of a Debt - more than 5000/- [1(i)(b)]",
    StampDutyTypeKarnataka.KA_NRG_128: "Acknowledgement of a Debt - upto Rs.5000/- [1(i)(a)]",
    StampDutyTypeKarnataka.KA_RG_24: "Administration Bond [2]",
    StampDutyTypeKarnataka.KA_NRG_2: "Administration Bond - In any other case [2(B)]",
    StampDutyTypeKarnataka.KA_NRG_112: "Administration Bond - Upto Rs.1000/- [2(a)]",
    StampDutyTypeKarnataka.KA_NRG_3: "Adoption Deed [3]",
    StampDutyTypeKarnataka.KA_RG_1: "Adoption Deed [3]",
    StampDutyTypeKarnataka.KA_NRG_4: "Affidavit [4]",
    StampDutyTypeKarnataka.KA_RG_25: "Affidavit [4]",
    StampDutyTypeKarnataka.KA_RG_67: "Agreement (In any other cases) [5(J)]",
    StampDutyTypeKarnataka.KA_NRG_22: "Agreement (in any other cases) [5(J)]",
    StampDutyTypeKarnataka.KA_RG_76: "Agreement or Memorandum of Agreement For opening DMAT Account [5(i)(i-a)]",
    StampDutyTypeKarnataka.KA_NRG_19: "Agreement or its records or MOA - Agreement relating to building works or labour or services Above Rs.10 lakhs [5(i-d)(ii)]",
    StampDutyTypeKarnataka.KA_NRG_10: "Agreement or its records or MOA - In any other case [5(c)(ii)]",
    StampDutyTypeKarnataka.KA_NRG_11: "Agreement or its records or MOA - Sale of immovable property wherein part performance of the contract, possession of the contract, possession of the property is not delivered [5(e)(ii)]",
    StampDutyTypeKarnataka.KA_NRG_12: "Agreement or its records or MOA - Sale of moveable property, possession of the property is delivered [5(g)(i)]",
    StampDutyTypeKarnataka.KA_NRG_13: "Agreement or its records or MOA - Sale of moveable property, possession of the property is not delivered [5(g)(ii)]",
    StampDutyTypeKarnataka.KA_NRG_16: "Agreement relating to Advertisement or telecasting or broadcasting of programs [5(i-b)]",
    StampDutyTypeKarnataka.KA_NRG_15: "Agreement relating to Contract between Stock Broker or Sub Broker (agent) and client for Stock Market Operations [5(i-a)]",
    StampDutyTypeKarnataka.KA_NRG_23: "Agreement relating to DTD - Loan amount does not exceed Rs.10 lakhs [6(1)(i)]",
    StampDutyTypeKarnataka.KA_NRG_24: "Agreement relating to DTD - Loan amount exceeding Rs.10 lakhs [6(1)(ii)]",
    StampDutyTypeKarnataka.KA_RG_27: "Agreement relating to Deposit of Title Deed [6]",
    StampDutyTypeKarnataka.KA_RG_26: "Agreement relating to Sale of Immoveable property [5]",
    StampDutyTypeKarnataka.KA_NRG_17: "Agreement relating to assignment or transfer of intellectual property rights, patent rights, copy rights or trade market rights [5(i-c)]",
    StampDutyTypeKarnataka.KA_NRG_18: "Agreement relating to building works or labour or services - Upto Rs.10 lakhs [5(i-d)(i)]",
    StampDutyTypeKarnataka.KA_NRG_14: "Agreement relating to contract between Depository Participant and Client for opening Demat A/c [5(i)]",
    StampDutyTypeKarnataka.KA_RG_28: "Appointment in execution of a power [7]",
    StampDutyTypeKarnataka.KA_NRG_27: "Appointment in execution of a power [7]",
    StampDutyTypeKarnataka.KA_RG_29: "Appraisement or Valuation [8]",
    StampDutyTypeKarnataka.KA_NRG_29: "Appraisement or Valuation - In any other case [8(b)]",
    StampDutyTypeKarnataka.KA_NRG_28: "Appraisement or Valuation - Upto Rs.1000 [8(a)]",
    StampDutyTypeKarnataka.KA_RG_30: "Apprenticeship Deed [9]",
    StampDutyTypeKarnataka.KA_NRG_30: "Apprenticeship Deed [9]",
    StampDutyTypeKarnataka.KA_RG_31: "Article of Association [10]",
    StampDutyTypeKarnataka.KA_NRG_31: "Articles of Association of a Company [10]",
    StampDutyTypeKarnataka.KA_RG_32: "Award other than partition Award [11]",
    StampDutyTypeKarnataka.KA_NRG_126: "Bank Guarantee - If related to paper bank guarantee [56(i)]",
    StampDutyTypeKarnataka.KA_NRG_127: "Bank Guarantee - If relating to e-bank guarantee [56(ii)]",
    StampDutyTypeKarnataka.KA_RG_33: "Bond [12]",
    StampDutyTypeKarnataka.KA_NRG_33: "Bond - Amount exceeding Rs.1000 [12(b)]",
    StampDutyTypeKarnataka.KA_NRG_32: "Bond - Amount secured does not exceed Rs.1000 [12(a)]",
    StampDutyTypeKarnataka.KA_NRG_34: "Bottomry Bond [13]",
    StampDutyTypeKarnataka.KA_RG_34: "Bottomry Bond [13]",
    StampDutyTypeKarnataka.KA_RG_2: "Cancellation of Instruments [14]",
    StampDutyTypeKarnataka.KA_RG_79: "Cancellation of any pf executed instrument in NeSL web portal Only [14(a,b,c)]",
    StampDutyTypeKarnataka.KA_RG_35: "Certificate [16]",
    StampDutyTypeKarnataka.KA_NRG_38: "Certificate evidencing right or title of the holder thereof, or any other person, either to any share, scrip or stock in or of any incorporated company [16]",
    StampDutyTypeKarnataka.KA_NRG_39: "Certificate of Enrolment as Advocate [17]",
    StampDutyTypeKarnataka.KA_RG_36: "Certificate of Enrolment as Advocate [17]",
    StampDutyTypeKarnataka.KA_RG_3: "Certificate of Sale [15]",
    StampDutyTypeKarnataka.KA_NRG_37: "Certificate of Sale - In any other case [15(c)]",
    StampDutyTypeKarnataka.KA_NRG_35: "Certificate of Sale - Purchase money does not exceed Rs.10 [15(a)]",
    StampDutyTypeKarnataka.KA_NRG_36: "Certificate of Sale - Purchase money does not exceed Rs.25 [15(b)]",
    StampDutyTypeKarnataka.KA_RG_80: "Certificate of Sale for auctions executed in auction sites [15(a,b,c)]",
    StampDutyTypeKarnataka.KA_NRG_40: "Charter Party [18]",
    StampDutyTypeKarnataka.KA_RG_37: "Charter Party [18]",
    StampDutyTypeKarnataka.KA_RG_78: "Chit Agreement [5(i-e)(i)(ii)]",
    StampDutyTypeKarnataka.KA_NRG_20: "Chit Agreement - Where the value of the chit does not exceed Rs.1 lakh [5(i-e)(i)]",
    StampDutyTypeKarnataka.KA_NRG_21: "Chit Agreement - Where the value of the chit exceeds Rs.1 lakh [5(i-e)(ii)]",
    StampDutyTypeKarnataka.KA_RG_38: "Clearance List [18(A)]",
    StampDutyTypeKarnataka.KA_NRG_44: "Composition Deed [19]",
    StampDutyTypeKarnataka.KA_RG_4: "Composition Deed [19]",
    StampDutyTypeKarnataka.KA_RG_5: "Conveyance [20]",
    StampDutyTypeKarnataka.KA_NRG_114: "Conveyance - Industrial machinery treated as movable [20(5)(i)]",
    StampDutyTypeKarnataka.KA_NRG_46: "Copy of Extract [21]",
    StampDutyTypeKarnataka.KA_RG_6: "Copy of a extract [21]",
    StampDutyTypeKarnataka.KA_RG_7: "Counter part or Duplicate [22]",
    StampDutyTypeKarnataka.KA_NRG_47: "Counter part or Duplicate [22]",
    StampDutyTypeKarnataka.KA_RG_39: "Customs Bond [23]",
    StampDutyTypeKarnataka.KA_NRG_48: "Customs Bond or Excise Bond Art 23(b) [23]",
    StampDutyTypeKarnataka.KA_RG_68: "D.T.D. [6(1)]",
    StampDutyTypeKarnataka.KA_RG_72: "Deed of hypothecation [34(b)]",
    StampDutyTypeKarnataka.KA_RG_73: "Deed of hypothecation [34(d)]",
    StampDutyTypeKarnataka.KA_RG_40: "Delivery order in respect of Goods [24]",
    StampDutyTypeKarnataka.KA_NRG_49: "Delivery order in respect of Goods [24]",
    StampDutyTypeKarnataka.KA_RG_16: "Dissolution(with immoveable property) [40(C)]",
    StampDutyTypeKarnataka.KA_RG_53: "Dissolution(without immoveable property) [40(C)]",
    StampDutyTypeKarnataka.KA_NRG_50: "Divorce [25]",
    StampDutyTypeKarnataka.KA_RG_8: "Divorce [25]",
    StampDutyTypeKarnataka.KA_RG_9: "Exchange of Property [26]",
    StampDutyTypeKarnataka.KA_RG_10: "Further Charge [27]",
    StampDutyTypeKarnataka.KA_RG_81: "Further charge on mortgaged property with possession [27(a)]",
    StampDutyTypeKarnataka.KA_RG_82: "Further charge on mortgaged property without possession [27(b)(i,ii,iii)]",
    StampDutyTypeKarnataka.KA_NRG_52: "Further charges Hypothecation of Movable property loan upto 10 Lakhs 34(d)(i) [27(b)(iii)]",
    StampDutyTypeKarnataka.KA_NRG_53: "Further charges Loan exceeding 10 Lakhs 34(d)(ii) [27(b)(iii)]",
    StampDutyTypeKarnataka.KA_RG_11: "Gift [28]",
    StampDutyTypeKarnataka.KA_RG_41: "Indemnity Bond [29]",
    StampDutyTypeKarnataka.KA_NRG_54: "Indemnity Bond (As per Article 47) [29]",
    StampDutyTypeKarnataka.KA_RG_42: "Lease of Immovable Property [30]",
    StampDutyTypeKarnataka.KA_NRG_55: "Lease of Immovable Property - Not exceeding 1 year in case of Residential property [30(1)(i)]",
    StampDutyTypeKarnataka.KA_NRG_56: "Lease of Immovable Property - Not exceeding 1 year in case of commercial industrial property [30(1)(ii)]",
    StampDutyTypeKarnataka.KA_NRG_58: "Lease of Movable Property - Above 10 years [30(2)(a)(ii)]",
    StampDutyTypeKarnataka.KA_NRG_60: "Lease of Movable Property - Lease for fine premium and also rent [30(2)(c)]",
    StampDutyTypeKarnataka.KA_NRG_59: "Lease of Movable Property - Lease granted for fine or premium but no rent [30(2)(b)]",
    StampDutyTypeKarnataka.KA_NRG_57: "Lease of Movable Property - Lease of movable property rent fixed, no premium30(2)(a)(i)upto 10 years [30(2)]",
    StampDutyTypeKarnataka.KA_RG_74: "Lease of immovable property-Not exceeding 1 year [30(i)]",
    StampDutyTypeKarnataka.KA_RG_43: "Letter of Allotment [31]",
    StampDutyTypeKarnataka.KA_NRG_61: "Letter of Allotment [31]",
    StampDutyTypeKarnataka.KA_RG_44: "Letter of License [32]",
    StampDutyTypeKarnataka.KA_NRG_64: "Letter of License - 1 year to 10 year [32-A(iii)]",
    StampDutyTypeKarnataka.KA_NRG_65: "Letter of License - 10 year to 20 year [32-A(iv)]",
    StampDutyTypeKarnataka.KA_NRG_66: "Letter of License - 20 to 30 year [32-A(v)]",
    StampDutyTypeKarnataka.KA_NRG_63: "Letter of License - Not more than 1 year in case of commercial industrial property [32-A(ii)]",
    StampDutyTypeKarnataka.KA_NRG_62: "Letter of License - Not more than 1 year in case of residential property [32-A (i)]",
    StampDutyTypeKarnataka.KA_NRG_125: "Letter of licence [32]",
    StampDutyTypeKarnataka.KA_RG_45: "License of Immovable and Movable Property [32(A)]",
    StampDutyTypeKarnataka.KA_NRG_85: "Limited Liability Partnership - Capital Upto Rs.10 lakhs [40A(a)]",
    StampDutyTypeKarnataka.KA_NRG_86: "Limited Liability Partnership - Capital more than Rs.10 lakhs [40A(b)]",
    StampDutyTypeKarnataka.KA_NRG_87: "Limited Liability Partnership - Reconstruction or Amalgamation [40B]",
    StampDutyTypeKarnataka.KA_RG_46: "Memorandum of Association of a company [33]",
    StampDutyTypeKarnataka.KA_NRG_67: "Memorandum of Association of a company [33]",
    StampDutyTypeKarnataka.KA_RG_12: "Mortgage Deed [34]",
    StampDutyTypeKarnataka.KA_NRG_68: "Mortgage Deed - Hypothecation of movable property loan upto Rs.10 lakh [34(d)(i)]",
    StampDutyTypeKarnataka.KA_NRG_69: "Mortgage Deed - loan exceeding 10 lakhs [34(d)(ii)]",
    StampDutyTypeKarnataka.KA_RG_83: "Mortgage deed For hypothecation of movable property [34(d)(i,ii)]",
    StampDutyTypeKarnataka.KA_RG_47: "Mortgage of a Crop [35]",
    StampDutyTypeKarnataka.KA_RG_84: "Mortgage of a crop [35(a,b)]",
    StampDutyTypeKarnataka.KA_RG_70: "Mortgage with Possession [34(a)]",
    StampDutyTypeKarnataka.KA_RG_71: "Mortgage without Possession [34(b)]",
    StampDutyTypeKarnataka.KA_RG_48: "Notarial Act [36]",
    StampDutyTypeKarnataka.KA_RG_50: "Note of Protest by the Master of a ship [38]",
    StampDutyTypeKarnataka.KA_NRG_76: "Note of Protest by the Master of a ship [38]",
    StampDutyTypeKarnataka.KA_RG_49: "Note or Memorandum [37]",
    StampDutyTypeKarnataka.KA_NRG_72: "Note or memorandum of record sent by broker to his principal intimating the purchase or sale through stock exchange of a Government Securities [37(c)]",
    StampDutyTypeKarnataka.KA_NRG_70: "Note or memorandum of record sent by broker to his principal intimating the purchase or sale through stock exchange of any goods or commodities [37(a)]",
    StampDutyTypeKarnataka.KA_NRG_71: "Note or memorandum of record sent by broker to his principal intimating the purchase or sale through stock exchange of any share, scrip, stock, bond, debenture (other than Government Security) [37(b)]",
    StampDutyTypeKarnataka.KA_NRG_75: "Note or memorandum of record sent by broker to his principal intimating the purchase or sale through stock exchange of forward contracts commodities [37(f)]",
    StampDutyTypeKarnataka.KA_NRG_74: "Note or memorandum of record sent by broker to his principal intimating the purchase or sale through stock exchange of futures and options trading of securities [37(e)]",
    StampDutyTypeKarnataka.KA_NRG_73: "Note or memorandum of record sent by broker to his principal intimating the purchase or sale through stock exchange other Securities [37(d)]",
    StampDutyTypeKarnataka.KA_RG_13: "Partition [39]",
    StampDutyTypeKarnataka.KA_NRG_79: "Partition - Agricultural Land [39(b)]",
    StampDutyTypeKarnataka.KA_NRG_81: "Partition - Combination of all above [39(d)]",
    StampDutyTypeKarnataka.KA_NRG_80: "Partition - Movable Property [39(c)]",
    StampDutyTypeKarnataka.KA_NRG_77: "Partition - Non Agricultural property in BBMP, UDA, BMRDA, Municipal Councils or Town Panchayats [39(a)(1)]",
    StampDutyTypeKarnataka.KA_NRG_78: "Partition - Other Areas [39(a)(2)]",
    StampDutyTypeKarnataka.KA_NRG_82: "Partnership - Constitution of Partnership [40 (A)]",
    StampDutyTypeKarnataka.KA_NRG_84: "Partnership - Dissolution [40(C)]",
    StampDutyTypeKarnataka.KA_NRG_124: "Partnership - Dissolution -  Immovable properties [40(C)(b)]",
    StampDutyTypeKarnataka.KA_NRG_83: "Partnership - Reconstitution [40(B)(b)]",
    StampDutyTypeKarnataka.KA_RG_14: "Partnership:(with immoveable property) [40(A)]",
    StampDutyTypeKarnataka.KA_RG_51: "Partnership:(without immoveable property) [40(A)]",
    StampDutyTypeKarnataka.KA_RG_69: "Pawn or Pledge [6(2)]",
    StampDutyTypeKarnataka.KA_NRG_25: "Pawn or Pledge of Movable Property - Loan amount above Rs.1 lakh and upto Rs.10 lakh [6(2)(i)]",
    StampDutyTypeKarnataka.KA_NRG_26: "Pawn or Pledge of Movable Property - Loan amount above Rs.10 lakhs [6(2)(ii)]",
    StampDutyTypeKarnataka.KA_RG_54: "Power of Attorney [41]",
    StampDutyTypeKarnataka.KA_NRG_90: "Power of Attorney - Authorizing to sell property [41(e)]",
    StampDutyTypeKarnataka.KA_NRG_89: "Power of Attorney - authorizing more than 5 to 10 persons to act jointly in more than one transaction or generally [41(d)]",
    StampDutyTypeKarnataka.KA_NRG_113: "Power of Attorney - for admitting executing of document [41(a)]",
    StampDutyTypeKarnataka.KA_NRG_116: "Power of Attorney - for authorising more than 5 person to act jointly [41(c)]",
    StampDutyTypeKarnataka.KA_NRG_115: "Power of Attorney - for authorising one or more person to act in a single transaction [41(b)]",
    StampDutyTypeKarnataka.KA_NRG_96: "Power of Attorney - in any other case [41(h)]",
    StampDutyTypeKarnataka.KA_NRG_95: "Power of Attorney - when given for depository participant [41(g)]",
    StampDutyTypeKarnataka.KA_NRG_94: "Power of Attorney - when given for trading operation [41(f)]",
    StampDutyTypeKarnataka.KA_NRG_92: "Power of Attorney - when sale power given to other than family members [41(eb)]",
    StampDutyTypeKarnataka.KA_NRG_98: "Protest by the Master of a Ship [43]",
    StampDutyTypeKarnataka.KA_RG_56: "Protest by the Master of a Ship [43]",
    StampDutyTypeKarnataka.KA_RG_55: "Protest of Bill [42]",
    StampDutyTypeKarnataka.KA_NRG_97: "Protest of Bill / Note [42]",
    StampDutyTypeKarnataka.KA_NRG_119: "Purchase or Sale of Government Securities - 37(c) [18A(1)]",
    StampDutyTypeKarnataka.KA_NRG_118: "Purchase or Sale of Government Securities - 5(b) [18A(1)]",
    StampDutyTypeKarnataka.KA_NRG_8: "Purchase or Sale of Government Security [5(b)]",
    StampDutyTypeKarnataka.KA_NRG_99: "Re-Conveyance of mortgaged property [44]",
    StampDutyTypeKarnataka.KA_RG_17: "Re-conveyance of Mortgage [44]",
    StampDutyTypeKarnataka.KA_RG_15: "Reconstitution(with immoveable property) [40(B)]",
    StampDutyTypeKarnataka.KA_RG_52: "Reconstitution(without immoveable property) [40(B)]",
    StampDutyTypeKarnataka.KA_RG_77: "Relating to building works or labour or service (work contact) [5(i-d)(i)(ii)]",
    StampDutyTypeKarnataka.KA_RG_18: "Release [45]",
    StampDutyTypeKarnataka.KA_RG_57: "Respodentia Bond [46]",
    StampDutyTypeKarnataka.KA_NRG_100: "Respondentia Bond - Amount Secured does not exceed Rs.1000 [12(a)]",
    StampDutyTypeKarnataka.KA_NRG_101: "Respondentia Bond - Amount exceeding Rs.1000 [12(b)]",
    StampDutyTypeKarnataka.KA_NRG_7: "Sale of Bill Exchange [5(a)]",
    StampDutyTypeKarnataka.KA_NRG_9: "Sale or Purchase of Shares, Stocks Bonds, Debenture Stock or other marketable security between members of Stock Exchange [5(c)(i)]",
    StampDutyTypeKarnataka.KA_NRG_121: "Securities of incorporated company of other body corporate submitted to clearing house office stock exchange recognized under the Securities Contract (regulartion) Act, 1956. - 37(b) [18A(2)]",
    StampDutyTypeKarnataka.KA_NRG_120: "Securities of incorporated company of other body corporate submitted to clearing house office stock exchange recognized under the Securities Contract (regulartion) Act, 1956. - 5(c)(i) [18A(2)]",
    StampDutyTypeKarnataka.KA_NRG_123: "Securities of incorporated company or other body corporate submitted to clearing house office stock exchange not recognized under the securities contract (regulation) Act, 1956. - 37(b) [18A(3)]",
    StampDutyTypeKarnataka.KA_NRG_122: "Securities of incorporated company or other body corporate submitted to clearing house office stock exchange not recognized under the securities contract (regulation) Act, 1956. - 5(c)(i) [18A(3)]",
    StampDutyTypeKarnataka.KA_RG_58: "Security Bond or Mortgage Deed [47]",
    StampDutyTypeKarnataka.KA_NRG_102: "Security Bond or Mortgage Deed [47]",
    StampDutyTypeKarnataka.KA_RG_19: "Settlement [48]",
    StampDutyTypeKarnataka.KA_RG_59: "Share Warrants [49]",
    StampDutyTypeKarnataka.KA_NRG_103: "Share Warrants [49]",
    StampDutyTypeKarnataka.KA_RG_60: "Shipping [50]",
    StampDutyTypeKarnataka.KA_NRG_104: "Shipping [50]",
    StampDutyTypeKarnataka.KA_RG_61: "Surrender of Lease [51]",
    StampDutyTypeKarnataka.KA_RG_20: "Surrender of Lease [51]",
    StampDutyTypeKarnataka.KA_NRG_105: "Surrender of Lease (Art 40b) [51]",
    StampDutyTypeKarnataka.KA_RG_62: "Transfer [52]",
    StampDutyTypeKarnataka.KA_NRG_117: "Transfer - property under section 25 of administrator generals act 1963. [52(c)]",
    StampDutyTypeKarnataka.KA_NRG_107: "Transfer any interest secured by bond or policy of insurance [52(b)]",
    StampDutyTypeKarnataka.KA_RG_21: "Transfer of Lease [53]",
    StampDutyTypeKarnataka.KA_RG_63: "Transfer of Lease [53]",
    StampDutyTypeKarnataka.KA_NRG_108: "Transfer of Licence [53A]",
    StampDutyTypeKarnataka.KA_RG_64: "Transfer of License [53(A)]",
    StampDutyTypeKarnataka.KA_NRG_106: "Transfer of debentures [52(a)]",
    StampDutyTypeKarnataka.KA_RG_22: "Trust [54]",
    StampDutyTypeKarnataka.KA_RG_65: "Trust [54]",
    StampDutyTypeKarnataka.KA_NRG_110: "Trust made for management and custody of property where there is no transfer / disposition of property [54(ii)]",
    StampDutyTypeKarnataka.KA_NRG_109: "Trust made for public religious and charitable purpose [54(i)]",
    StampDutyTypeKarnataka.KA_RG_66: "Warrant of Goods [55]",
    StampDutyTypeKarnataka.KA_NRG_111: "Warrants of Goods [55]"
}