from .PB_stamp_duty import StampDutyTypePunjab

stamp_duty_display_names_punjab = {
    StampDutyTypePunjab.PB_RG_1: "Acknowledgement of a debt [1]",
    StampDutyTypePunjab.PB_RG_2: "Administration Bond [2]",
    StampDutyTypePunjab.PB_RG_3: "Adoption-Deed [3]",
    StampDutyTypePunjab.PB_RG_4: "Affidavit [4]",
    StampDutyTypePunjab.PB_RG_66: "Agreement - if not otherwise provided for [5(d)]",
    StampDutyTypePunjab.PB_RG_69: "Agreement of Memorandum of an Agreement - if relating to the sale of a Government security or share in an incorporated company or other body corporate [5(b)]",
    StampDutyTypePunjab.PB_RG_68: "Agreement of Memorandum of an Agreement - if relating to the sale of a bill of exchange [5(a)]",
    StampDutyTypePunjab.PB_RG_70: "Agreement of Memorandum of an Agreement - if relating to the sale of immovable property [5(c)]",
    StampDutyTypePunjab.PB_RG_71: "Agreement of Memorandum of an Agreement - in the case of agreement to sell followed by or evidencing delivery of possession of the immovable property agreed to be sold [5(cc)]",
    StampDutyTypePunjab.PB_RG_5: "Agreement or Memorandum of an Agreement [5]",
    StampDutyTypePunjab.PB_RG_6: "Agreement relating to Deposit of Title- Deeds, Pawn or Pledge [6]",
    StampDutyTypePunjab.PB_RG_67: "Agreement relating to deposit of title deeds, pawn or pledge, mortgage by way of deposit of Title Deed (Equitable Mortgage) and hypothecation [6]",
    StampDutyTypePunjab.PB_RG_7: "Appointment in Execution of a Power [7]",
    StampDutyTypePunjab.PB_RG_8: "Appraisement or Valuation [8]",
    StampDutyTypePunjab.PB_RG_9: "Apprenticeship-Deed [9]",
    StampDutyTypePunjab.PB_RG_10: "Articles of Association of a Company [10]",
    StampDutyTypePunjab.PB_RG_11: "Articles of Clerkship [11]",
    StampDutyTypePunjab.PB_RG_12: "Award [12]",
    StampDutyTypePunjab.PB_RG_13: "Bill of Exchange [13]",
    StampDutyTypePunjab.PB_RG_14: "Bill of Lading (including a through bill of lading) [14]",
    StampDutyTypePunjab.PB_RG_15: "Bond [15]",
    StampDutyTypePunjab.PB_RG_16: "Bottomary Bond [16]",
    StampDutyTypePunjab.PB_RG_17: "Cancellation [17]",
    StampDutyTypePunjab.PB_RG_18: "Certificate of Sale [18]",
    StampDutyTypePunjab.PB_RG_19: "Certificate of other Document [19]",
    StampDutyTypePunjab.PB_RG_20: "Charter Party [20]",
    StampDutyTypePunjab.PB_RG_21: "Composition-Deed [22]",
    StampDutyTypePunjab.PB_RG_22: "Conveyance [23]",
    StampDutyTypePunjab.PB_RG_23: "Copy or Extract [24]",
    StampDutyTypePunjab.PB_RG_24: "Counterpart or Duplicate [25]",
    StampDutyTypePunjab.PB_RG_25: "Customs-Bonds [26]",
    StampDutyTypePunjab.PB_RG_26: "Debenture [27]",
    StampDutyTypePunjab.PB_RG_27: "Delivery order in respect of goods, deposit of title deeds [28]",
    StampDutyTypePunjab.PB_RG_28: "Divorce [29]",
    StampDutyTypePunjab.PB_RG_29: "Entry as an Advocate, Vakil or Attorney on the roll of the High Court [30]",
    StampDutyTypePunjab.PB_RG_30: "Exchange of Property [31]",
    StampDutyTypePunjab.PB_RG_31: "Further Charge [32]",
    StampDutyTypePunjab.PB_RG_32: "Gift [33]",
    StampDutyTypePunjab.PB_RG_33: "Indemnity Bond [34]",
    StampDutyTypePunjab.PB_RG_34: "Lease [35]",
    StampDutyTypePunjab.PB_RG_35: "Letter of Allotment of Shares [36]",
    StampDutyTypePunjab.PB_RG_36: "Letter of Credit [37]",
    StampDutyTypePunjab.PB_RG_37: "Letter of License [38]",
    StampDutyTypePunjab.PB_RG_38: "Memorandum of Association of a Company [39]",
    StampDutyTypePunjab.PB_RG_39: "Mortgage Deed [40]",
    StampDutyTypePunjab.PB_RG_40: "Mortgage of a Crop [41]",
    StampDutyTypePunjab.PB_RG_41: "Notarial Act [42]",
    StampDutyTypePunjab.PB_RG_42: "Note or Memorandum [43]",
    StampDutyTypePunjab.PB_RG_43: "Note of Protest by the Master of a Ship [44]",
    StampDutyTypePunjab.PB_RG_44: "Partition [45]",
    StampDutyTypePunjab.PB_RG_45: "Partnership [46]",
    StampDutyTypePunjab.PB_RG_46: "Policy of Insurance [47]",
    StampDutyTypePunjab.PB_RG_47: "Power of Attorney [48]",
    StampDutyTypePunjab.PB_RG_48: "Promissory Note [49]",
    StampDutyTypePunjab.PB_RG_49: "Protest of Bill or Note [50]",
    StampDutyTypePunjab.PB_RG_50: "Protest by the Master of a Ship [51]",
    StampDutyTypePunjab.PB_RG_51: "Proxy [52]",
    StampDutyTypePunjab.PB_RG_52: "Receipt [53]",
    StampDutyTypePunjab.PB_RG_53: "Reconveyance of Mortgaged Property [54]",
    StampDutyTypePunjab.PB_RG_54: "Release [55]",
    StampDutyTypePunjab.PB_RG_55: "Respondentia Bond [56]",
    StampDutyTypePunjab.PB_RG_56: "Security-Bond or Mortgage Deed [57]",
    StampDutyTypePunjab.PB_RG_57: "Settlement [58]",
    StampDutyTypePunjab.PB_RG_58: "Share Warrants [59]",
    StampDutyTypePunjab.PB_RG_59: "Shipping Order [60]",
    StampDutyTypePunjab.PB_RG_60: "Surrender of Lease [61]",
    StampDutyTypePunjab.PB_RG_61: "Transfer [62]",
    StampDutyTypePunjab.PB_RG_62: "Transfer of Lease [63]",
    StampDutyTypePunjab.PB_RG_63: "Trust [64]",
    StampDutyTypePunjab.PB_RG_64: "Warrant for Goods [65]",
}