# Mapping of Enum to human-readable 
from .raj_stamp_duty import StampDutyType

stamp_duty_display_names = {
    StampDutyType.RJ_RG_1267: 'Lease Deed (Rent Deed) between private parties- (i) Lease deed period less than 1 year to 30 years [33(i) to (vi)]',
    StampDutyType.RJ_RG_759: 'Amendment in Article of Association of a company if relating to increase in authorised share capital in any other case [11]',
    StampDutyType.RJ_RG_229: '(a) Gift in favour of widow by her deceased husband\'s mother, father, brother, or sister [31]',
    StampDutyType.RJ_RG_230: '(b) Gift in favour of widow by her own mother, father, brother, sister, son or daughter [31]',
    StampDutyType.RJ_RG_662: '(b) Mortgage Deed without possession [37(b)]',
    StampDutyType.RJ_RG_102: 'Acknowledgment [1]',
    StampDutyType.RJ_RG_103: 'Administration Bond [2]',
    StampDutyType.RJ_RG_1071: 'Administration Bond - (i) Administration Bond (Gen.) [2]',
    StampDutyType.RJ_RG_1072: 'Administration Bond - (ii) Administration Bond under sections 291, 375, 376 of the Indian Succession Act, 1925 [2]',
    StampDutyType.RJ_RG_1073: 'Administration Bond - (iii) Administration Bond under section 6 of the Government Savings Bank Act, 1873 [2]',
    StampDutyType.RJ_RG_1: 'Adoption [3]',
    StampDutyType.RJ_RG_104: 'Affidavit [4]',
    StampDutyType.RJ_RG_469: 'Affidavit (MukhyaMantri Shahari Jan Kalyan Yojana) [4]',
    StampDutyType.RJ_RG_16: 'Agreement [5] / Agreement [5(c)]',
    StampDutyType.RJ_RG_1225: 'Agreement - Any agreement not covered under Art. 5(a) to 5(ff) (iv) [5(g)]',
    StampDutyType.RJ_RG_4: 'Agreement / Power of Development [5(bbbb)]',
    StampDutyType.RJ_RG_171: 'Agreement Relating to Deposit of Title Deed, pawn or pledge when Loan is repayable in more than 3 months [6(a)]',
    StampDutyType.RJ_RG_172: 'Agreement Relating to Deposit of Title Deed, pawn or pledge when Loan is repayable in not more than 3 months [6(b)]',
    StampDutyType.RJ_RG_578: 'Agreement Relating to Deposit of Title Deed / Equitable Mortgage Deed when Loan not more than 3 months [6(ii)]',
    StampDutyType.RJ_RG_101: 'Agreement Relating to Deposit of Title Deed / Equitable Mortgage Deed when Loan not more than 3 months [6(ii)]',
    StampDutyType.RJ_RG_577: 'Agreement Relating to Deposit of Title Deed / Equitable Mortgage Deed when Loan repayable in more than 3 months [6(i)]',
    StampDutyType.RJ_RG_100: 'Agreement Relating to Deposit of Title Deed / Equitable Mortgage Deed when Loan repayable in more than 3 months [6(i)]',
    StampDutyType.RJ_RG_568: 'Agreement between Bank and Merchant for Point of Sale Machine (POS) [5(d)]',
    StampDutyType.RJ_RG_567: 'Agreement conferring exclusive rights of telecasting, broadcasting or exhibition, event or film. In any other case [5(ff)(ii)]',
    StampDutyType.RJ_RG_166: 'Agreement conferring rights of telecasting, broadcasting or exhibition, event or film of amount exceeding rupees 10 lakhs [5(ff)(i)]',
    StampDutyType.RJ_RG_165: 'Agreement conferring rights of telecasting, broadcasting or exhibition, event or film of amount up to rupees 10 lakhs [5(ff)]',
    StampDutyType.RJ_RG_3: 'Agreement of Loan [5(bbb)]',
    StampDutyType.RJ_RG_757: 'Agreement or any other document Relating to Deposit of Title Deed, pawn or pledge / Equitable Mortgage Deed when Loan not more than 3 months (ii) [6]',
    StampDutyType.RJ_RG_756: 'Agreement or any other document Relating to Deposit of Title Deed, pawn or pledge / Equitable Mortgage Deed when Loan repayable in more than 3 months (i) [6]',
    StampDutyType.RJ_RG_1226: 'Agreement relating to POS (v) [5]',
    StampDutyType.RJ_RG_1222: 'Agreement relating to advertisement (i) [5(f)]',
    StampDutyType.RJ_RG_398: 'Agreement relating to advertisement for promotion of product, program or event [5(f)]',
    StampDutyType.RJ_RG_164: 'Agreement relating to advertisement for promotion of product, program or event of amount exceeding rupees 10 lakhs [5(f)(ii)]',
    StampDutyType.RJ_RG_163: 'Agreement relating to advertisement for promotion of product, program or event of amount up to rupees 10 lakhs [5(f)(i)]',
    StampDutyType.RJ_RG_1214: 'Agreement relating to sale of Govt. securities or share of incorporated company or body [5(b)]',
    StampDutyType.RJ_RG_1213: 'Agreement relating to sale of a bill of Exchange [5(a)]',
    StampDutyType.RJ_RG_1224: 'Agreement relating to telecasting, broadcasting or exhibition, event or film - of amount exceeding Rs. 10 Lac (iii) [5(ff)(ii)]',
    StampDutyType.RJ_RG_1223: 'Agreement relating to telecasting, broadcasting or exhibition, event or film - of amount up to Rs. 10 Lac (ii) [5(ff)(i)]',
    StampDutyType.RJ_RG_569: 'Agreement to Sale executed between Developer and purchaser Under Chief Minister Jan Aawas Yojna-2015 for sale of residential unit [5(d)]',
    StampDutyType.RJ_RG_755: 'Agreement to Sale executed between Developer and purchaser Under Chief Minister Jan Aawas Yojna-2015 for sale of residential unit [5]',
    StampDutyType.RJ_RG_5: 'Agreement to Sale with Possession [23] / [21(ii)]',
    StampDutyType.RJ_RG_1229: 'Agreement to Sale with possession for residential unit between Developer and purchaser Under CM Jan Aawas Yojna (ii) [5(c)]',
    StampDutyType.RJ_RG_1228: 'Agreement to Sale with possession for residential unit between Developer and purchaser Under CM Jan Aawas Yojna for EWS (i) [5(c)]',
    StampDutyType.RJ_RG_2: 'Agreement to Sale without Possession [5(bb)]',
    StampDutyType.RJ_RG_1227: 'Agreement to Sale without possession for residential unit between Developer and purchaser Under CM Jan Aawas Yojna [5(c)]',
    StampDutyType.RJ_RG_1297: 'Agreement to Sale without possession for residential unit between Developer and purchaser Under CM Jan Aawas Yojna LIG [5(c)]',
    StampDutyType.RJ_RG_1215: 'Agreement to sale of immovable property without possession or promise of possession [5(c)]',
    StampDutyType.RJ_RG_754: 'Agreement to sale with possession [5]',
    StampDutyType.RJ_RG_1012: 'Agreement to sale with possession (Disabled Between 40% to 80%) [21(i)]',
    StampDutyType.RJ_RG_162: 'Agreement to sale with possession (disable 40% or above) [21(1)]',
    StampDutyType.RJ_RG_566: 'Agreement to sale with possession (disabled) [21(i)]',
    StampDutyType.RJ_RG_565: 'Agreement to sale with possession (female SC/ST/BPL) [21(i)]',
    StampDutyType.RJ_RG_161: 'Agreement to sale with possession (female SC/ST/BPL) [21(1)]',
    StampDutyType.RJ_RG_564: 'Agreement to sale with possession (female) [21(i)]',
    StampDutyType.RJ_RG_160: 'Agreement to sale with possession (female) [21(1)]',
    StampDutyType.RJ_RG_159: 'Agreement to sale with possession (male) [21(1)]',
    StampDutyType.RJ_RG_563: 'Agreement to sale with possession (male) [21(i)]',
    StampDutyType.RJ_RG_397: 'Agreement to sale without possession [5(c)]',
    StampDutyType.RJ_RG_1102: 'Allotment or sale of immovable property in favour of Rajasthan State Electricity Companies upto 31.03.2024 [21(i)]',
    StampDutyType.RJ_RG_68: 'Amalgamation order by high court [21(iii)]',
    StampDutyType.RJ_RG_206: 'Amalgamation order of companies and bank by HC/RBI [21(iii)]',
    StampDutyType.RJ_RG_1256: 'Amendment in AOA of a Non - Profit Company (5) [11]',
    StampDutyType.RJ_RG_1252: 'Amendment in AOA of a Raj. Govt. Company (3) - for increase in authorised share Capital (i) [11]',
    StampDutyType.RJ_RG_1253: 'Amendment in AOA of a Raj. Govt. Company (3) - in any other case (ii) [11]',
    StampDutyType.RJ_RG_1254: 'Amendment in AOA of other than Raj. Govt. Company (4) - for increase in authorised share Capital (i) [11]',
    StampDutyType.RJ_RG_1255: 'Amendment in AOA of other than Raj. Govt. Company (4) - in any other case (ii) [11]',
    StampDutyType.RJ_RG_758: 'Amendment in Article of Association of a company if relating to increase in authorised share capital [11]',
    StampDutyType.RJ_RG_174: 'Amendment in Article of Association of a company not relating to increase in authorized share capital [11(ii)]',
    StampDutyType.RJ_RG_173: 'Amendment in Article of Association of a company relating to increase in authorized share capital [11(i)]',
    StampDutyType.RJ_RG_71: 'Amendment in Articles of Association of a Company [11]',
    StampDutyType.RJ_RG_1425: 'Any Category of Loan Document: Instruments executed for sanctioning loan under the Rajasthan Cooperative Gopal Credit Card Loan Scheme [37(b)]',
    StampDutyType.RJ_RG_1416: 'Any Document related to movable property',
    StampDutyType.RJ_RG_1415: 'Any document executed by or on behalf of or in favour of Govt. where liability on SD is on Govt.',
    StampDutyType.RJ_RG_111: 'Appointment in execution of a power [7]',
    StampDutyType.RJ_RG_400: 'Appraisement of valuation where amount is exceeding Rs. 1,000/- [8(b)]',
    StampDutyType.RJ_RG_112: 'Appraisement of valuation - Where the amount does not exceed Rs. 1,000/- [8(a)]',
    StampDutyType.RJ_RG_113: 'Appraisement of valuation - in any other case [8(b)]',
    StampDutyType.RJ_RG_1401: 'Appraisement or valuation made otherwise than under and order of the court in the course of a suit [8]',
    StampDutyType.RJ_RG_114: 'Apprenticeship-deed [9]',
    StampDutyType.RJ_RG_1407: 'Arms License New (a)- (ix) Licence in Form XI-A [35-A(b)(iv)]',
    StampDutyType.RJ_RG_1404: 'Arms License New (a)- (vi) Licence in Form VIII [35-A(b)(i)]',
    StampDutyType.RJ_RG_1405: 'Arms License New (a)- (vii) Licence in Form VIII-A [35-A(b)(ii)]',
    StampDutyType.RJ_RG_1406: 'Arms License New (a)- (viii) Licence in Form XI [35-A(b)(iii)]',
    StampDutyType.RJ_RG_1408: 'Arms License New (a)- (x) Licence in Form XIV [35-A(b)(v)]',
    StampDutyType.RJ_RG_1298: 'Arms License New (a)-(i) Revolvers or pistols [35-A(a)(i)]',
    StampDutyType.RJ_RG_1299: 'Arms License New (a)-(ii) Rifles [35-A(a)(ii)]',
    StampDutyType.RJ_RG_1300: 'Arms License New (a)-(iii) DBBL Weapons [35-A(a)(iii)]',
    StampDutyType.RJ_RG_1301: 'Arms License New (a)-(iv) SBBL Weapons [35-A(a)(iv)]',
    StampDutyType.RJ_RG_1306: 'Arms License New (a)-(ix) Licence in Form XIV [35-A(b)(iv)]',
    StampDutyType.RJ_RG_1302: 'Arms License New (a)-(v) ML Weapons [35-A(a)(v)]',
    StampDutyType.RJ_RG_1303: 'Arms License New (a)-(vi) Licence in Form XI [35-A(b)(i)]',
    StampDutyType.RJ_RG_1304: 'Arms License New (a)-(vii) Licence in Form XII [35-A(b)(ii)]',
    StampDutyType.RJ_RG_1305: 'Arms License New (a)-(viii) Licence in Form XIII [35-A(b)(iii)]',
    StampDutyType.RJ_RG_1412: 'Arms License Renewal (b)-(ix) Licence in Form XI-A [35-A(d)(iv)]',
    StampDutyType.RJ_RG_1409: 'Arms License Renewal (b)-(vi) Licence in Form VIII [35-A(d)(i)]',
    StampDutyType.RJ_RG_1410: 'Arms License Renewal (b)-(vii) Licence in Form VIII-A [35-A(d)(ii)]',
    StampDutyType.RJ_RG_1411: 'Arms License Renewal (b)-(viii) Licence in Form XI [35-A(d)(iii)]',
    StampDutyType.RJ_RG_1413: 'Arms License Renewal (b)-(x) Licence in Form XIV [35-A(d)(v)]',
    StampDutyType.RJ_RG_1307: 'Arms License Renewal (b)-(i) Revolvers or pistols [35-A(c)(i)]',
    StampDutyType.RJ_RG_1308: 'Arms License Renewal (b)-(ii) Rifles [35-A(c)(ii)]',
    StampDutyType.RJ_RG_1309: 'Arms License Renewal (b)-(iii) DBBL Weapons [35-A(c)(iii)]',
    StampDutyType.RJ_RG_1310: 'Arms License Renewal (b)-(iv) SBBL Weapons [35-A(c)(iv)]',
    StampDutyType.RJ_RG_1315: 'Arms License Renewal (b)-(ix) Licence in Form XIV [35-A(d)(iv)]',
    StampDutyType.RJ_RG_1311: 'Arms License Renewal (b)-(v) ML Weapons [35-A(c)(v)]',
    StampDutyType.RJ_RG_1312: 'Arms License Renewal (b)-(vi) Licence in Form XI [35-A(d)(i)]',
    StampDutyType.RJ_RG_1313: 'Arms License Renewal (b)-(vii) Licence in Form XII [35-A(d)(ii)]',
    StampDutyType.RJ_RG_1314: 'Arms License Renewal (b)-(viii) Licence in Form XIII [35-A(d)(iii)]',
    StampDutyType.RJ_RG_70: 'Article of Association of a Company [10]',
    StampDutyType.RJ_RG_115: 'Articles of clerkship [12]',
    StampDutyType.RJ_RG_826: 'Assignment Deed for assigning rights in lease deed – in any other case [33]',
    StampDutyType.RJ_RG_825: 'Assignment Deed for assigning rights in lease deed – under Rajasthan Township Policy, 2010 [33]',
    StampDutyType.RJ_RG_1156: 'Assignment Deed for transferring lease rights – in any other case (ii) [33]',
    StampDutyType.RJ_RG_1155: 'Assignment Deed for transferring lease rights – under Rajasthan Township Policy, 2002/2010 (i) [33]',
    StampDutyType.RJ_RG_1101: 'Assignment of copyright under Copyright Act, 1957 [21]',
    StampDutyType.RJ_RG_1107: 'Auction sale of property for MSME revival [17]',
    StampDutyType.RJ_RG_676: 'Authentication Power of Attorney [44]',
    StampDutyType.RJ_RG_6: 'Award [13]',
    StampDutyType.RJ_RG_706: 'Award - any other case [13(ii)]',
    StampDutyType.RJ_RG_705: 'Award - property value does not exceed ₹1,000 [13(i)]',
    StampDutyType.RJ_RG_175: 'Award - property value does not exceed ₹1,000 [13(a)]',
    StampDutyType.RJ_RG_176: 'Award - property value exceeds ₹1,000 [13(b)]',
    StampDutyType.RJ_RG_1402: 'Award - subject matter is immovable property [13(a)]',
    StampDutyType.RJ_RG_1403: 'Award - subject matter is movable property [13(b)]',
    StampDutyType.RJ_RG_79: 'Bank Guarantee [13A]',
    StampDutyType.RJ_RG_72: 'Bond [14]',
    StampDutyType.RJ_RG_116: 'Bottomry Bond [15]',
    StampDutyType.RJ_RG_7: 'Cancellation Deed [16]',
    StampDutyType.RJ_RG_1396: 'Cancellation - by Local Authority [16]',
    StampDutyType.RJ_RG_1397: 'Cancellation - any other case [16]',
    StampDutyType.RJ_RG_1392: 'Cancellation - after one month (ii) [16]',
    StampDutyType.RJ_RG_1394: 'Cancellation - after one month (ii) Disabled 40%-80% [16]',
    StampDutyType.RJ_RG_1395: 'Cancellation - after one month (ii) Female (Non-SC/ST/BPL) [16]',
    StampDutyType.RJ_RG_1393: 'Cancellation - after one month (ii) Female (SC/ST/BPL) [16]',
    StampDutyType.RJ_RG_1391: 'Cancellation - within one month (i) [16]',
    StampDutyType.RJ_RG_8: 'Certificate of Sale [17]',
    StampDutyType.RJ_RG_178: 'Certificate of Sale (Female SC/ST/BPL) [17]',
    StampDutyType.RJ_RG_179: 'Certificate of Sale (Female other than SC/ST/BPL) [17]',
    StampDutyType.RJ_RG_180: 'Certificate of Sale (Disabled 40% or above) [17]',
    StampDutyType.RJ_RG_830: 'Certificate of Sale - Public Auction [17]',
    StampDutyType.RJ_RG_1013: 'Certificate of Sale - Public Auction (Disabled 40%-80%) [17]',
    StampDutyType.RJ_RG_831: 'Certificate of Sale - Public Auction (Disabled) [17]',
    StampDutyType.RJ_RG_833: 'Certificate of Sale - Public Auction (Female Non-SC/ST/BPL) [17]',
    StampDutyType.RJ_RG_832: 'Certificate of Sale - Public Auction (Female SC/ST/BPL) [17]',
    StampDutyType.RJ_RG_712: 'Certificate of Sale - MSME Policy 2015 [17]',
    StampDutyType.RJ_RG_715: 'Certificate of Sale - MSME Policy (Female other than disabled) [17]',
    StampDutyType.RJ_RG_713: 'Certificate of Sale - MSME Policy (Female SC/ST/BPL) [17]',
    StampDutyType.RJ_RG_714: 'Certificate of Sale - MSME Policy (Female Non-SC/ST/BPL) [17]',
    StampDutyType.RJ_RG_1105: 'Certificate of Sale - Commercial plot ≤ 50 sq. yd. (iii) [21(i)]',
    StampDutyType.RJ_RG_1106: 'Certificate of Sale - Senior Citizen (60+ yrs) (iv) [21(i)]',
    StampDutyType.RJ_RG_1104: 'Certificate of Sale - Plot ≤ 100 sq. yd. (ii) [21(i)]',
    StampDutyType.RJ_RG_73: 'Certificate or other document [18]',
    StampDutyType.RJ_RG_117: 'Charter Party [19]',
    StampDutyType.RJ_RG_181: 'Composition Deed - Property to creditors (Male) [20(i)]',
    StampDutyType.RJ_RG_183: 'Composition Deed - Property to creditors (Female non-SC/ST/BPL) [20(i)]',
    StampDutyType.RJ_RG_182: 'Composition Deed - Property to creditors (Female SC/ST/BPL) [20(i)]',
    StampDutyType.RJ_RG_184: 'Composition Deed - Property to creditors (Disabled 40%+) [20(i)]',
    StampDutyType.RJ_RG_579: 'Composition Deed - General [20(i)]',
    StampDutyType.RJ_RG_1014: 'Composition Deed - General (Disabled 40%-80%) [20(i)]',
    StampDutyType.RJ_RG_580: 'Composition Deed - Female SC/ST/BPL [20(i)]',
    StampDutyType.RJ_RG_581: 'Composition Deed - Female other than SC/ST/BPL [20(i)]',
    StampDutyType.RJ_RG_582: 'Composition Deed - Disabled 40% or above [20(i)]',
    StampDutyType.RJ_RG_185: 'Composition Deed - Any other case [20(ii)]',
    StampDutyType.RJ_RG_583: 'Composition Deed - Any other case [20(ii)]',
    StampDutyType.RJ_RG_74: 'Composition-deed [20]',
    StampDutyType.RJ_RG_145: 'Concent Deed for mining [58]',
    StampDutyType.RJ_RG_474: 'Concession Agreement [20A]',
    StampDutyType.RJ_RG_118: 'Concession Agreement [20A]',
    StampDutyType.RJ_RG_186: 'Concession Agreement total capital investment upto 10 crores [20A(i)]',
    StampDutyType.RJ_RG_191: 'Concession Agreement: Total Capital Investment exceed rupees 1000 crore but not exceed rupees 2500 crore [20A(vi)]',
    StampDutyType.RJ_RG_189: 'Concession Agreement: Total Capital Investment exceed rupees 200 crore but not exceed rupees 500 crore [20A(iv)]',
    StampDutyType.RJ_RG_192: 'Concession Agreement: Total Capital Investment exceed rupees 2500 crore [20A(vii)]',
    StampDutyType.RJ_RG_188: 'Concession Agreement: Total Capital Investment exceed rupees 50 crore but not exceed rupees 200 crore [20A(iii)]',
    StampDutyType.RJ_RG_190: 'Concession Agreement: Total Capital Investment exceed rupees 500 crore but not exceed rupees 1000 crore [20A(v)]',
    StampDutyType.RJ_RG_187: 'Concession Agreement: Total Capital investment exceed rupees 10 crore but not exceed rupees 50 crore [20A(ii)]',
    StampDutyType.RJ_RG_765: 'Consent Deed (i) Agriculture land purchased for mining purpose or consent deed for mining purpose between land owner and lessee. [21]',
    StampDutyType.RJ_RG_1292: 'Consent Deed : Agriculture land purchased for mining purpose or consent deed for mining purpose between land owner and lessee. [21(i)]',
    StampDutyType.RJ_RG_1293: 'Consent Deed : Agriculture land purchased for mining purpose or consent deed for mining purpose between land owner and lessee. (Female SC/ST/BPL) [21(i)]',
    StampDutyType.RJ_RG_1294: 'Consent Deed : Agriculture land purchased for mining purpose or consent deed for mining purpose between land owner and lessee. (Female other than SC/ST/BPL) [21(i)]',
    StampDutyType.RJ_RG_1295: 'Consent Deed : Agriculture land purchased for mining purpose or consent deed for mining purpose between land owner and lessee.(Disabled Between 40% to 80%) [21(i)]',
    StampDutyType.RJ_RG_51: 'Consent Deed for mining lease [21]',
    StampDutyType.RJ_RG_1015: 'Consent Deed- Agriculture land purchased for mining purpose or consent deed for mining purpose (in favour of Disabled Between 40% to 80%) (iv) [21]',
    StampDutyType.RJ_RG_723: 'Consent Deed- Agriculture land purchased for mining purpose or consent deed for mining purpose (in favour of disabled persons 40% or above) (iv) [21]',
    StampDutyType.RJ_RG_722: 'Consent Deed- Agriculture land purchased for mining purpose or consent deed for mining purpose (in favour of female SC/ST/BPL) (iii) [21]',
    StampDutyType.RJ_RG_721: 'Consent Deed- Agriculture land purchased for mining purpose or consent deed for mining purpose (in favour of female other than SC/ST/BPL) (ii) [21]',
    StampDutyType.RJ_RG_720: 'Consent Deed- Agriculture land purchased for mining purpose or consent deed for mining purpose (in favour of male) (i) [21]',
    StampDutyType.RJ_RG_1093: 'Conveyance deed in favour of EWS/LIG by ULBs (i) EWS - Carpet area- 325 sq. ft. Family income- Rs. 5000/- p.m. [21(i)]',
    StampDutyType.RJ_RG_1094: 'Conveyance deed in favour of EWS/LIG by ULBs (ii) LIG - Carpet area- 500 sq. ft. Family income- Rs. 5001-Rs. 10000/- p.m. [21(i)]',
    StampDutyType.RJ_RG_1098: 'Conveyance deed in favour of family members of martyr by Govt./ULBs/ of Residential flat/ house - if the martyr was unmarried, then in favour of father (iv) [21(i)]',
    StampDutyType.RJ_RG_1099: 'Conveyance deed in favour of family members of martyr by Govt./ULBs/ of Residential flat/ house - if the martyr was unmarried, then in favour of mother (v) [21(i)]',
    StampDutyType.RJ_RG_1096: 'Conveyance deed in favour of family members of martyr by Govt./ULBs/ of Residential flat/ house - if the wife is not alive, then in favour of minor daughter (ii) [21(i)]',
    StampDutyType.RJ_RG_1097: 'Conveyance deed in favour of family members of martyr by Govt./ULBs/ of Residential flat/ house - if the wife is not alive, then in favour of minor son (iii) [21(i)]',
    StampDutyType.RJ_RG_1095: 'Conveyance deed in favour of family members of martyr by Govt./ULBs/ of Residential flat/ house - in favour of wife of martyr (i) [21(i)]',
    StampDutyType.RJ_RG_1346: 'Conveyance deed in favour of family members of martyr by Govt./ULBs/ of Residential flat/ house- if the in martyr was widower and having no minor children then in favour of father or mother. (vi) [21(i)]',
    StampDutyType.RJ_RG_1091: 'Conveyance deed of immovable property from sponsoring body to private university [21(i)]',
    StampDutyType.RJ_RG_588: 'Conveyance deed regarding Resi flat or house executed by State Govt or local auth or any other auth of State Govt in fav of wife of martyr,if the wife of martyr is not alive,then in fav of either minor daughter or minor son and if the in martyr was unmarried,then in fav of either father or mother [21(i)]',
    StampDutyType.RJ_RG_1103: 'Conveyance of immovable property upto the value of Rs. 50 Lac in favour of any Start-Up having more than 50% equity with founder members of 18 to 35 years of age [21(i)]',
    StampDutyType.RJ_RG_584: 'Conveyence Deed Under SFS Scheme of Housing Board if the Stamp Duty paid as per rule in perpitual lease of this purpose [21(i)]',
    StampDutyType.RJ_RG_197: 'Conveyence Deed Under SFS Scheme of Housing Board if the proper stamp duty paid on perpitual lease of land [21(i)]',
    StampDutyType.RJ_RG_66: 'Copy of Document [22]',
    StampDutyType.RJ_RG_1077: 'Copy or Extract certified to be a true copy or extract by public officer- (i) Copy if stamp duty on the original has not been paid [22]',
    StampDutyType.RJ_RG_1078: 'Copy or Extract certified to be a true copy or extract by public officer- (ii) if the original was not chargeable with duty or if chargeable the duty does not exceed 1 rupee [22(i)]',
    StampDutyType.RJ_RG_1079: 'Copy or Extract certified to be a true copy or extract by public officer- (iii) in any other case [22(ii)]',
    StampDutyType.RJ_RG_1080: 'Copy or Extract certified to be a true copy or extract by public officer- (iv) Copy of any paper made or furnished by public officer for record in any public office for any public purpose [22]',
    StampDutyType.RJ_RG_1399: 'Copy or Extract certified to be a true copy or extract by public officer- Copy or extract certified to be a true copy or extract, by or by order of any public officer and not chargeable under the law for the time being in force relating to court fees [22]',
    StampDutyType.RJ_RG_1081: 'Copy or Extract certified to be a true copy or extract by public officer-(v) Copy or Extract from any register relating to birth, baptism, namings, dedications, marriages, divorces, deaths or burialsn [22]',
    StampDutyType.RJ_RG_589: 'Copy or extract (ii) in any other case [22]',
    StampDutyType.RJ_RG_209: 'Copy or extract if the original was chargeable with duty exceeding Rs. 1 [22(ii)]',
    StampDutyType.RJ_RG_208: 'Copy or extract if the original was not chargeable with duty or if chargeable the duty does not exceed Rs. 1 [22(i)]',
    StampDutyType.RJ_RG_10: 'Counter Part / Duplicate [23]',
    StampDutyType.RJ_RG_590: 'Counter Part or Duplicate (Original not exceed Three rupees) [23(a)]',
    StampDutyType.RJ_RG_591: 'Counter Part or Duplicate In any other case [23(b)]',
    StampDutyType.RJ_RG_1263: 'Counter Part or Duplicate of any instrument- Counter Part or Duplicate if stamp duty on the original has been paid (ii) - Counter Part of a Lease granted to a cultivator and such lease is exempted from SD (c) [23]',
    StampDutyType.RJ_RG_1262: 'Counter Part or Duplicate of any instrument- Counter Part or Duplicate if stamp duty on the original has been paid (ii) - In any other case (b) [23(b)]',
    StampDutyType.RJ_RG_1261: 'Counter Part or Duplicate of any instrument- Counter Part or Duplicate if stamp duty on the original has been paid (ii) - if stamp duty on original not exceeds Rs. 3/- (a) [23(a)]',
    StampDutyType.RJ_RG_1260: 'Counter Part or Duplicate of any instrument- Counter Part or Duplicate if stamp duty on the original has not been paid (i) [23]',
    StampDutyType.RJ_RG_1400: 'Counter Part or Duplicate of any instrument- Counterpart or duplicate of any instrument chargeable with duty and in respect of which the proper duty has been paid [23]',
    StampDutyType.RJ_RG_211: 'Counter Part or Duplicate: if the duty payable on original exceed Rs. 3 [23(b)]',
    StampDutyType.RJ_RG_210: 'Counter Part or Duplicate: if the duty payable on original not exceed Rs. 3 [23(a)]',
    StampDutyType.RJ_RG_75: 'Custom Bond [25]',
    StampDutyType.RJ_RG_348: 'Debt assignment (non performing assets) [21(i)]',
    StampDutyType.RJ_RG_347: 'Debt assignment (performing assets) [21(i)]',
    StampDutyType.RJ_RG_403: 'Debt assignment by bank or financial institution in favor of Asset Reconstruction Company [21(i)]',
    StampDutyType.RJ_RG_1345: 'Debt assignment- Security receipts issued under sub-section (1) and (2) of section 7 of the Securitisation and Reconstruction of Financial Assets and Enforcement of Security Interest Act, 2002 (Central Act No. 54 of 2002) (iv) [21(i)]',
    StampDutyType.RJ_RG_699: 'Declaration of Trust - in any other case - in respect of immovable property [56(A)(a)(ii)]',
    StampDutyType.RJ_RG_702: 'Declaration of Trust - in any other case - in respect of immovable property (Disable 40% and above) [56(A)(a)(ii)]',
    StampDutyType.RJ_RG_1016: 'Declaration of Trust - in any other case - in respect of immovable property (Disabled Between 40% to 80%) [56(A)(a)(ii)]',
    StampDutyType.RJ_RG_700: 'Declaration of Trust - in any other case - in respect of immovable property (Female SC/ST/BPL) [56(A)(a)(ii)]',
    StampDutyType.RJ_RG_701: 'Declaration of Trust - in any other case - in respect of immovable property (Female other than SC/ST/BPL) [56(A)(a)(ii)]',
    StampDutyType.RJ_RG_703: 'Declaration of Trust - in respect of other property [56(A)(a)(ii)]',
    StampDutyType.RJ_RG_698: 'Declaration of Trust - where there is disposition of property,- where the trust is made for a religious or charitable purpose [56(A)(a)(i)]',
    StampDutyType.RJ_RG_704: 'Declaration of Trust - where there is no disposition of property [56(A)(b)]',
    StampDutyType.RJ_RG_1087: 'Deemed Conveyance/Sale Conveyance Deed Under SFS Scheme of RHB [21(i)]',
    StampDutyType.RJ_RG_1083: 'Deemed Conveyance/Sale : (ii) Final conveyance or lease or any other document executed in pursuance of agreement or power of attorney or instrument mentioned in (i) above [21(i)]',
    StampDutyType.RJ_RG_1086: 'Deemed Conveyance/Sale : (ii) Final conveyance or lease or any other document executed in pursuance of agreement or power of attorney or instrument mentioned in (i) above (Disabled Between 40% to 80%) [21(i)]',
    StampDutyType.RJ_RG_1084: 'Deemed Conveyance/Sale : (ii) Final conveyance or lease or any other document executed in pursuance of agreement or power of attorney or instrument mentioned in (i) above (Female SC/ST/BPL) [21(i)]',
    StampDutyType.RJ_RG_1085: 'Deemed Conveyance/Sale : (ii) Final conveyance or lease or any other document executed in pursuance of agreement or power of attorney or instrument mentioned in (i) above (Female other than SC/ST/BPL) [21(i)]',
    StampDutyType.RJ_RG_1082: 'Deemed Conveyance/Sale : Agreement to sell, Irrevocable Power of Attorney or any other instrument executed in course of Conveyance or Lease or Mortgage etc. of Immovable property i.e. Allotment letter, Patta, License with possession or with promise of possession (i) [21(i)]',
    StampDutyType.RJ_RG_120: 'Delivery order in respect of goods [26]',
    StampDutyType.RJ_RG_766: 'Delivery order in respect of goods,excluding delivery order in respect of settlement of transactions in securities in stock exchange [26]',
    StampDutyType.RJ_RG_1195: 'Deposit of Title Deed/Pawn/Pledge- when loan is repayable in more than3 months (i) [6(i)]',
    StampDutyType.RJ_RG_1196: 'Deposit of Title Deed/Pawn/Pledge- when loan is repayable within3 months (ii) [6(ii)]',
    StampDutyType.RJ_RG_69: 'Developer Agreement [5(e)]',
    StampDutyType.RJ_RG_149: 'Developer Agreement (Sale power not given) [5(e)]',
    StampDutyType.RJ_RG_150: 'Developer Agreement (Sale power) [5(e)]',
    StampDutyType.RJ_RG_1221: 'Developer Agreement where stamp duty has been paid under Article44(eee) on the Power of Attorney executed between same parties in respect of same property [5(e)]',
    StampDutyType.RJ_RG_1387: 'Developer Agreement- Developer Agreement where stamp duty has been paid under Article44(f) on the Power of Attorney executed between same parties in respect of same property [5(e)]',
    StampDutyType.RJ_RG_1430: 'Developer Agreement- When given to promoter or developer for sale or transfer of any immovable property [5(e)]',
    StampDutyType.RJ_RG_1417: 'Developer Agreement- part of developer property as consideration and his given power to sale that part of the developer property [5(e)]',
    StampDutyType.RJ_RG_1386: 'Developer Agreement- part of developer property as consideration and his given power to sale that part of the developer property with sale power (ii) [5(e)]',
    StampDutyType.RJ_RG_1385: 'Developer Agreement- without sale power (i) [5(e)]',
    StampDutyType.RJ_RG_30: 'Dissolution of Partnership [43]',
    StampDutyType.RJ_RG_862: 'Dissolution of limited liability partnership: (a) where the immovable property is brought in by any partner as his share contribution at the time of constitution of the limited liability partnership and such property is taken by any other partner as his share on dissolution [35-B(4)(a)]',
    StampDutyType.RJ_RG_863: 'Dissolution of limited liability partnership: (b) where immovable property is acquired by the limited liability partnership after its constitution and such property is distributed among the partners on dissolution [35-B(4)(b)]',
    StampDutyType.RJ_RG_1237: 'Dissolution of partnership (2) - where such partnership was between grandfather, grandmother, father, mother, brother, sister, son, daughter, grandson, granddaughter, husband and wife (aa) [43(2)(a)]',
    StampDutyType.RJ_RG_1238: 'Dissolution of partnership (2) - where such partnership was between grandfather, grandmother, father, mother, brother, sister, son, daughter, grandson, granddaughter, husband and wife (bb) [43(2)(b)]',
    StampDutyType.RJ_RG_546: 'Dissolution of partnership(2) (a) where the immovable property is brought in by any partner as his share contribution at the time of constitution of the partnership and such property is taken by any other partner as his share on dissolution. [43]',
    StampDutyType.RJ_RG_547: 'Dissolution of partnership(2) (b) where immovable property is acquired by the partnership after its constitution and such property is distributed among the partners on dissolution. [43]',
    StampDutyType.RJ_RG_548: 'Dissolution of partnership(2) (b) where immovable property is acquired by the partnership after its constitution and such property is distributed among the partners on dissolution. If the partners in such partnership are father, mother and sons [43]',
    StampDutyType.RJ_RG_667: 'Dissolution of partnership(b.b)where immov propty is acquired by partnership after its constitution and such property is distributed among partners on distion.If partnership is between grandfather,grandmother,father,mother,brother,sister,son,daughter,grandson,granddaughter,husband and wife. [43]',
    StampDutyType.RJ_RG_666: 'DissolutionOfPartnership(2)(aa)WhereImmov.ProptyBroughtInByAnyPartnerAs HisShareContributionAtTimeOfConstitution ofPrtnrshipandSuchProptyIsTakenByAny OthrPartnerAsHisShareOnDistion.IfPrtnrshipIsBetweenGrandfatherGrandmotherFatherMotherBrotherSisterSonDaughterGrandsonGranddaughterHusband and Wife [43]',
    StampDutyType.RJ_RG_12: 'Divorce Deed [27]',
    StampDutyType.RJ_RG_1219: 'Education Loan Agreement by or on behalf of student (iv) [5(d)]',
    StampDutyType.RJ_RG_121: 'Entry as an advocate, on the roll of any High Court [28]',
    StampDutyType.RJ_RG_1265: 'Entry as an advocate, on the roll of any High Court- Entry as an advocate, on the roll of any High Court if he is already enrolled in a High Court (ii) [28]',
    StampDutyType.RJ_RG_1264: 'Entry as an advocate, on the roll of any High Court- Entry as an advocate, on the roll of any High Court if he is already not enrolled in a High Court (i) [28]',
    StampDutyType.RJ_RG_13: 'Exchange Deed [29]',
    StampDutyType.RJ_RG_214: 'Exchange Deed (40% or) [29]',
    StampDutyType.RJ_RG_62: 'Exchange Deed (Agriculture US-48 RTA) [29]',
    StampDutyType.RJ_RG_707: 'Exchange Deed (Disable40% and above) [29]',
    StampDutyType.RJ_RG_1017: 'Exchange Deed (Disabled Between40% to80%) [29]',
    StampDutyType.RJ_RG_212: 'Exchange Deed (Female SC/ST/BPL) [29]',
    StampDutyType.RJ_RG_213: 'Exchange Deed (Female other than SC/ST/BPL) [29]',
    StampDutyType.RJ_RG_1360: 'Exchange Deed executed for non agriculture properties in favour of family member \'Family Member\' means father, mother, husband, wife, brother, sister, son, daughter, son\'s son, son\'s daughter, daughter\'s son, daughter\'s daughter and daughter in law of settler. [29]',
    StampDutyType.RJ_RG_1356: 'Exchange Deed other than family member [29]',
    StampDutyType.RJ_RG_1357: 'Exchange Deed other than family member (Disabled Between40% to80%) [29]',
    StampDutyType.RJ_RG_1359: 'Exchange Deed other than family member (Female SC/ST/BPL) [29]',
    StampDutyType.RJ_RG_1358: 'Exchange Deed other than family member (Female other than SC/ST/BPL) [29]',
    StampDutyType.RJ_RG_382: 'Family settlement between family members (father, mother, wife, brother, sister, son, daughter, grandson, granddaughter, daughter in law of settler [51(A)(ii)]',
    StampDutyType.RJ_RG_14: 'Further charge with possession [30(a)]',
    StampDutyType.RJ_RG_597: 'Further charge with possession (Disable40% and above) [30(a)]',
    StampDutyType.RJ_RG_1018: 'Further charge with possession (Disabled Between40% to80%) [30(a)]',
    StampDutyType.RJ_RG_595: 'Further charge with possession (Female SC/ST/BPL) [30(a)]',
    StampDutyType.RJ_RG_596: 'Further charge with possession (Female other than SC/ST/BPL) [30(a)]',
    StampDutyType.RJ_RG_594: 'Further charge with possession (a) (i) [30]',
    StampDutyType.RJ_RG_15: 'Further charge without possession [30(b)]',
    StampDutyType.RJ_RG_598: 'Further charge without possession :- (i) possession is given, or agreed to be given in original mortgage [30(b)(i)]',
    StampDutyType.RJ_RG_601: 'Further charge without possession :- (ii) if possession is not so given [30(b)(ii)]',
    StampDutyType.RJ_RG_599: 'Further charge without possession :- possession is given, or agreed to be given in original mortgage (Female SC/ST/BPL) [30(b)(i)]',
    StampDutyType.RJ_RG_600: 'Further charge without possession :-possession is given, or agreed to be given in original mortgage (Female other than SC/ST/BPL) [30(b)(i)]',
    StampDutyType.RJ_RG_716: 'Further charge without possession:- possession is given, or agreed to be given in original mortgage (Disable40% and above) [30(b)]',
    StampDutyType.RJ_RG_1019: 'Further charge without possession:- possession is given, or agreed to be given in original mortgage (Disabled Between40% to80%) [30(b)]',
    StampDutyType.RJ_RG_1199: 'Further charge- Further charge when original mortgage was with possession (a) [30(a)]',
    StampDutyType.RJ_RG_1202: 'Further charge- Further charge when original mortgage was with possession (a) (Disabled Between40% to80%) [30(a)]',
    StampDutyType.RJ_RG_1200: 'Further charge- Further charge when original mortgage was with possession (a) (Female SC/ST/BPL) [30(a)]',
    StampDutyType.RJ_RG_1201: 'Further charge- Further charge when original mortgage was with possession (a) (Female other than SC/ST/BPL) [30(a)]',
    StampDutyType.RJ_RG_1207: 'Further charge- Further charge when original mortgage was without possession but (b)- if possession is not so given (ii) [30(b)(ii)]',
    StampDutyType.RJ_RG_1203: 'Further charge- Further charge when original mortgage was without possession but (b)- possession of property is given, or agreed to be given at the time of execution of Further charge (i) [30(b)(i)]',
    StampDutyType.RJ_RG_1205: 'Further charge- Further charge when original mortgage was without possession but (b)- possession of property is given, or agreed to be given at the time of execution of Further charge (i) (Female other than SC/ST/BPL) [30(b)(i)]',
    StampDutyType.RJ_RG_1206: 'Further charge- Further charge when original mortgage was without possession but (b)- possession of property is given, or agreed to be given at the time of execution of Further charge (i) (Disabled Between40% to80%) [30(b)(i)]',
    StampDutyType.RJ_RG_1204: 'Further charge- Further charge when original mortgage was without possession but (b)- possession of property is given, or agreed to be given at the time of execution of Further charge (i) (Female SC/ST/BPL) [30(b)(i)]',
    StampDutyType.RJ_RG_215: 'Further charge: when in original mortgage possession is given, or agreed to be given [30(a)]',
    StampDutyType.RJ_RG_216: 'Further charge: when in original mortgage possession is given, or agreed to be given (Female SC/ST/BPL) [30(a)]',
    StampDutyType.RJ_RG_217: 'Further charge: when in original mortgage possession is given, or agreed to be given (Female other thanSC/ST/BPL) [30(a)]',
    StampDutyType.RJ_RG_218: 'Further charge: when in original mortgage possession is given, or agreed to be given (disabled) [30(b)]',
    StampDutyType.RJ_RG_223: 'Further charge: when possession is neither given in original mortgage nor in further charge [30(b)(ii)]',
    StampDutyType.RJ_RG_219: 'Further charge: when possession is not given in original mortgage but given in further charge [30(b)(i)]',
    StampDutyType.RJ_RG_221: 'Further charge: when possession is not given in original mortgage but given in further charge (Female other than SC/ST/BPL) [30(b)(i)]',
    StampDutyType.RJ_RG_222: 'Further charge: when possession is not given in original mortgage but given in further charge (disabled) [30(b)(i)]',
    StampDutyType.RJ_RG_220: 'Further charge: when possession is not given in original mortgage but given in further charge(Female SC/ST/BPL) [30(b)(i)]',
    StampDutyType.RJ_RG_146: 'General Agreement [5(g)]',
    StampDutyType.RJ_RG_24: 'Gift Deed [31]',
    StampDutyType.RJ_RG_52_a: 'Gift Deed (Close Relations as per circular154 dated9 Mar2011) [31]',
    StampDutyType.RJ_RG_52_b: 'Gift Deed (Close Relations as per notification154 dated9 Mar2011) [31]',
    StampDutyType.RJ_RG_767: 'Gift Instrument [31]',
    StampDutyType.RJ_RG_717: 'Gift Instrument (Disable40% and above) [31]',
    StampDutyType.RJ_RG_1020: 'Gift Instrument (Disabled Between40% to80%) [31]',
    StampDutyType.RJ_RG_225: 'Gift Instrument (Female SC/ST/BPL) [31]',
    StampDutyType.RJ_RG_226: 'Gift Instrument (Female other than SC/ST/BPL) [31]',
    StampDutyType.RJ_RG_224: 'Gift Instrument (Male) [31]',
    StampDutyType.RJ_RG_852: 'Gift deed of immobale property executed in favour of a Non-Profit Institution as defined and identified eligible for benefits under the provisions of the Social Security Investment Promotion Scheme,2021(stamp duty rebate on submission of Entitlement Certificate issued by competent authority under the Scheme) [31]',
    StampDutyType.RJ_RG_604: 'Gift deed regarding Residential flat or house executed by any person private in favour of wife of martyr, if the wife of martyr is not alive, then in favour of either minor daughter or minor son and if the in martyr was unmarried, then in favour of either father or mother. [31]',
    StampDutyType.RJ_RG_1070: 'Gift deed under SSIPS-2021- Gift deed of immovable property in favour of a Non-Profit Institution under Social Security Investment Promotion Scheme,2021 [31]',
    StampDutyType.RJ_RG_850: 'Gift in favor of daughter in law [31]',
    StampDutyType.RJ_RG_752: 'Gift in favor of daughter or daughter in law [31]',
    StampDutyType.RJ_RG_768: 'Gift in favor of father, mother, son, brother, sister or husband [31]',
    StampDutyType.RJ_RG_769: 'Gift in favor of sons son, sons daughter, daughters son or daughters daughter [31]',
    StampDutyType.RJ_RG_1064: 'Gift in favour of Govt., Local Bodies, Enterprise [31]',
    StampDutyType.RJ_RG_231: 'Gift in favour of Govt., Local Bodies, Govt. Enterprise [31]',
    StampDutyType.RJ_RG_1058: 'Gift in favour of Widow- by her deceased husbands brother [31]',
    StampDutyType.RJ_RG_1059: 'Gift in favour of Widow- by her deceased husbands sister [31]',
    StampDutyType.RJ_RG_1060: 'Gift in favour of Widow- by her own brother [31]',
    StampDutyType.RJ_RG_1063: 'Gift in favour of Widow- by her own daughter [31]',
    StampDutyType.RJ_RG_1061: 'Gift in favour of Widow- by her own sister [31]',
    StampDutyType.RJ_RG_1062: 'Gift in favour of Widow- by her own son [31]',
    StampDutyType.RJ_RG_1047: 'Gift in favour of brother [31]',
    StampDutyType.RJ_RG_932: 'Gift in favour of brother, sister or husband [31]',
    StampDutyType.RJ_RG_592: 'Gift in favour of daughter [31]',
    StampDutyType.RJ_RG_940: 'Gift in favour of daughters daughter [31]',
    StampDutyType.RJ_RG_939: 'Gift in favour of daughters son [31]',
    StampDutyType.RJ_RG_1068: 'Gift in favour of family members of martyr by private person of Residential flat/ house - if the in martyr was unmarried, then in favour of father [31]',
    StampDutyType.RJ_RG_1069: 'Gift in favour of family members of martyr by private person of Residential flat/ house - if the in martyr was unmarried, then in favour of mother [31]',
}




