from .up_stamp_duty import StampDutyTypeUttarPradesh

stamp_duty_display_names_uttarpradesh = {
    StampDutyTypeUttarPradesh.UP_RG_20: "Acknowledgement of a Debt अभिस्वीकृति [1]",
    StampDutyTypeUttarPradesh.UP_RG_21: "Administration Bond प्रशासन बंधपत्र [2]",
    StampDutyTypeUttarPradesh.UP_RG_22: "Adoption Deed दत्तक विलेख [3]",
    StampDutyTypeUttarPradesh.UP_NRG_3: "Affidavit शपथ पत्र [4]",
    StampDutyTypeUttarPradesh.UP_RG_23: "Affidavit शपथ पत्र [4]",
    StampDutyTypeUttarPradesh.UP_RG_1: "Agreement or Memorandum of an agreement करार या करार का ज्ञापन या इकरारनामा [5]",
    StampDutyTypeUttarPradesh.UP_RG_2: "Agreement relating to deposit of title deeds, pawn or pledge हक़-विलेखों के निक्षेपों , पनयम या गिरवी से सम्बंधित करार [6]",
    StampDutyTypeUttarPradesh.UP_NRG_5: "Appointment in Execution of a Power किसी अधिकार के कार्यान्वयन मैं नियुक्ति [7]",
    StampDutyTypeUttarPradesh.UP_RG_24: "Appointment in Execution of a Power किसी अधिकार के कार्यान्वयन मैं नियुक्ति [7]",
    StampDutyTypeUttarPradesh.UP_RG_26: "Appraisement or Valuation आंकना या मूल्यांकन [8]",
    StampDutyTypeUttarPradesh.UP_NRG_4: "Apprenticeship Deed शिक्षुता विलेख [9]",
    StampDutyTypeUttarPradesh.UP_RG_27: "Apprenticeship Deed शिक्षुता विलेख [9]",
    StampDutyTypeUttarPradesh.UP_RG_28: "Articles of Association of a Company कंपनी के संगम अनुच्छेद [10]",
    StampDutyTypeUttarPradesh.UP_RG_29: "Articles of Clerkship कलर्को की नियमावली [11]",
    StampDutyTypeUttarPradesh.UP_RG_3: "Award पंचाट [12]",
    StampDutyTypeUttarPradesh.UP_RG_4: "Bank Guarantee बैंक गारंटी [12 (A)]",
    StampDutyTypeUttarPradesh.UP_RG_63: "Bill of Exchange विनिमय पत्र [13]",
    StampDutyTypeUttarPradesh.UP_RG_5: "Bond बांड या बंधपत्र [15]",
    StampDutyTypeUttarPradesh.UP_RG_30: "Bottomry Bond पोत बंधपत्र [16]",
    StampDutyTypeUttarPradesh.UP_RG_31: "Cancellation रद्द कर देने की लिखत [17]",
    StampDutyTypeUttarPradesh.UP_RG_32: "Certificate of Enrolment under Section 22 of the Advocates Act,1961 नामांकन प्रमाणपत्र अधिवक्ता अधिनियम, 1961  की धारा २२ के अंतर्गत [17A]",
    StampDutyTypeUttarPradesh.UP_NRG_6: "Certificate of Enrolment under Section 22 of the Advocates Act,1961 नामांकन प्रमाणपत्र अधिवक्ता अधिनियम, 1961  की धारा २२ के अंतर्गत [17A]",
    StampDutyTypeUttarPradesh.UP_RG_33: "Certificate of Practice as Notary नोटरी के रूप में प्रैक्टिस प्रमाण-पत्र [17B]",
    StampDutyTypeUttarPradesh.UP_RG_6: "Certificate of Sale विक्रय प्रमाण पत्र [18]",
    StampDutyTypeUttarPradesh.UP_RG_34: "Certificate or other Document प्रमाण पत्र या अन्य दस्तावेज [19]",
    StampDutyTypeUttarPradesh.UP_RG_35: "Charter Party भाड़े पर पोत लेने की  संविदा [20]",
    StampDutyTypeUttarPradesh.UP_RG_36: "Composition Deed प्रशमन विलेख [22]",
    StampDutyTypeUttarPradesh.UP_RG_7: "Conveyance विक्रय विलेख , बैनामा या हस्तांतरण पत्र [23]",
    StampDutyTypeUttarPradesh.UP_NRG_7: "Copy or Extract प्रति या उद्धरण [24]",
    StampDutyTypeUttarPradesh.UP_RG_37: "Copy or Extract प्रति या उद्धरण [24]",
    StampDutyTypeUttarPradesh.UP_RG_38: "Counterpart or Duplicate प्रतिलेख या दूसरी प्रति [25]",
    StampDutyTypeUttarPradesh.UP_RG_39: "Customs-Bond सीमा-शुल्क बंधपत्र [26]",
    StampDutyTypeUttarPradesh.UP_RG_62: "Debenture डिवेंचर [27]",
    StampDutyTypeUttarPradesh.UP_NRG_2: "Deed of Hypothecation डीड आफ हाइपोथैकेशन [40]",
    StampDutyTypeUttarPradesh.UP_RG_40: "Delivery Order in respect of Goods माल की बाबत परिदान-आदेश [28]",
    StampDutyTypeUttarPradesh.UP_RG_41: "Divorce विवाह विच्छेद की लिखत [29]",
    StampDutyTypeUttarPradesh.UP_RG_8: "Exchange of property संपत्ति के विनिमय की लिखत [31]",
    StampDutyTypeUttarPradesh.UP_RG_9: "Further Charge अतिरिक्त भार की लिखत [32]",
    StampDutyTypeUttarPradesh.UP_NRG_1: "General Loan Agreement सामान्य ऋण अनुबंध [5c]",
    StampDutyTypeUttarPradesh.UP_RG_10: "Gift दान की लिखत [33]",
    StampDutyTypeUttarPradesh.UP_NRG_8: "Indemnity Bond क्षतिपूर्ति-बंधपत्र [34]",
    StampDutyTypeUttarPradesh.UP_RG_42: "Indemnity Bond क्षतिपूर्ति-बंधपत्र [34]",
    StampDutyTypeUttarPradesh.UP_RG_43: "Instrument Correcting a purely Clerical Error लिपिकीय त्रुटि को ठीक करने हेतु [34A]",
    StampDutyTypeUttarPradesh.UP_RG_11: "Lease पट्टा या किरायानामा [35]",
    StampDutyTypeUttarPradesh.UP_NRG_9: "Letter of License अनुज्ञप्ति-पत्र  या लाइसेंस [38]",
    StampDutyTypeUttarPradesh.UP_RG_45: "Letter of License अनुज्ञप्ति-पत्र  या लाइसेंस [38]",
    StampDutyTypeUttarPradesh.UP_RG_44: "Letters of Allotment of Shares शेयरों का आवंटन-पत्र [36]",
    StampDutyTypeUttarPradesh.UP_RG_46: "Licence relating to Arms or Ammunitions आयुध या गोला बारूद से सम्बंधित अनुज्ञप्ति [38A]",
    StampDutyTypeUttarPradesh.UP_RG_47: "Memorandum of Association of a Company कंपनी का संगम ज्ञापन [39]",
    StampDutyTypeUttarPradesh.UP_RG_12: "Mortgage Deed बंधक विलेख [40]",
    StampDutyTypeUttarPradesh.UP_RG_48: "Mortgage of a Crop फसल का बंधक [41]",
    StampDutyTypeUttarPradesh.UP_NRG_10: "Notarial Act नोटरी सम्बन्धी कार्य [42]",
    StampDutyTypeUttarPradesh.UP_RG_49: "Notarial Act नोटरी सम्बन्धी कार्य [42]",
    StampDutyTypeUttarPradesh.UP_RG_51: "Note of Protest by the Master of a ship पोत मास्टर द्वारा आपत्ति का टिप्पण [44]",
    StampDutyTypeUttarPradesh.UP_RG_50: "Note or Memorandum टिप्पणी का ज्ञापन [43]",
    StampDutyTypeUttarPradesh.UP_RG_13: "Partition विभाजन की लिखत [45]",
    StampDutyTypeUttarPradesh.UP_RG_52: "Patnership भागीदारी [46]",
    StampDutyTypeUttarPradesh.UP_RG_14: "Power of Attorney मुख्तारनामा [48]",
    StampDutyTypeUttarPradesh.UP_NRG_11: "Power of Attorney मुख्तारनामा [48]",
    StampDutyTypeUttarPradesh.UP_RG_54: "Protest by the Master of a Ship पोत मास्टर द्वारा आपत्ति [51]",
    StampDutyTypeUttarPradesh.UP_RG_53: "Protest of bill or Note बिल या नोट का प्रोटेस्ट [50]",
    StampDutyTypeUttarPradesh.UP_NRG_12: "Protest of bill or Note बिल या नोट का प्रोटेस्ट [50]",
    StampDutyTypeUttarPradesh.UP_RG_55: "Re-Conveyance of Mortgaged property बंधक की गई संपत्ति का प्रतिहस्तान्तरण [54]",
    StampDutyTypeUttarPradesh.UP_NRG_14: "Receipt रसीद [53]",
    StampDutyTypeUttarPradesh.UP_RG_64: "Receipt रसीद [53]",
    StampDutyTypeUttarPradesh.UP_RG_56: "Release निर्मुक्ति/ दस्तबरदारी [55]",
    StampDutyTypeUttarPradesh.UP_RG_57: "Respondentia Bond जहाजी माल [56]",
    StampDutyTypeUttarPradesh.UP_RG_58: "Security Bond or Mortgage Deed प्रतिभूति-बंधपत्र या बंधक विलेख [57]",
    StampDutyTypeUttarPradesh.UP_NRG_13: "Security Bond or Mortgage Deed प्रतिभूति-बंधपत्र या बंधक विलेख [57]",
    StampDutyTypeUttarPradesh.UP_RG_15: "Settlement - Instrument of (including a deed of dower) व्यवस्थापन / सेटलमेंट लिखित [58 (A)]",
    StampDutyTypeUttarPradesh.UP_RG_16: "Settlement - Revocation of व्यवस्थापन / सेटलमेंट प्रतिसंहरण [58 (B)]",
    StampDutyTypeUttarPradesh.UP_RG_59: "Share Warrants शेयर वारंट [59]",
    StampDutyTypeUttarPradesh.UP_RG_60: "Shipping Order पोत परिवहन आदेश [60]",
    StampDutyTypeUttarPradesh.UP_RG_61: "Surrender of Lease पट्टे का अभ्यर्पण [61]",
    StampDutyTypeUttarPradesh.UP_RG_17: "Transfer of Lease अंतरण [63]",
    StampDutyTypeUttarPradesh.UP_RG_18: "Trust - Declaration of ट्रस्ट या न्यास की घोषणा [64 (A)]",
    StampDutyTypeUttarPradesh.UP_RG_19: "Trust - Revocation of टट्रस्ट या न्यास  का प्रतिसंहरण [64 (B)]",
    StampDutyTypeUttarPradesh.UP_RG_25: "Warrant of Good माल के लिया वारंट [65]",
}